import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { refreshOverdueInvoicesAction } from "@/features/invoices/actions";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";
export const dynamic="force-dynamic";
export default async function OwnerInvoicesPage(){const invoices=await prisma.invoice.findMany({include:{client:true,project:true,paymentSchedule:true},orderBy:{createdAt:"desc"}});return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Invoices</p><h1 className="mt-3 font-display text-3xl font-extrabold">Amounts issued from project schedules.</h1></div><form action={refreshOverdueInvoicesAction}><Button variant="outline">Refresh overdue status</Button></form></div><Card className="mt-8 overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-border bg-surface-container/50 text-xs uppercase tracking-wide text-secondary"><tr><th className="px-5 py-4">Invoice</th><th className="px-5 py-4">Client</th><th className="px-5 py-4">Project</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Due</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{invoices.map((invoice)=><tr key={invoice.id} className="border-b border-border last:border-0"><td className="px-5 py-4"><Link href={`/owner/invoices/${invoice.id}`} className="font-semibold text-primary hover:underline">{invoice.invoiceNumber}</Link><p className="mt-1 text-xs text-secondary">{invoice.paymentSchedule?.title}</p></td><td className="px-5 py-4">{invoice.client.name}</td><td className="px-5 py-4">{invoice.project.title}</td><td className="px-5 py-4 font-semibold">{formatIdr(invoice.total.toString())}</td><td className="px-5 py-4 text-secondary">{invoice.dueDate?.toLocaleDateString("id-ID")??"—"}</td><td className="px-5 py-4"><Badge>{invoice.status.replaceAll("_"," ")}</Badge></td></tr>)}</tbody></table></div></CardContent></Card></>}
