import type { Locale } from "@/i18n/config";

type Dictionary = {
  nav: { services: string; portfolio: string; process: string; reviews: string; about: string; signIn: string; startProject: string };
  common: { search: string; viewAll: string; learnMore: string; back: string; save: string; loading: string; retry: string; signOut: string; notifications: string; noData: string; archive: string; restore: string; archived: string; activeRecords: string; archiveRecords: string; archivedAt: string; results: string; clearFilters: string; all: string };
  auth: { welcome: string; loginTitle: string; loginDescription: string; email: string; password: string; signingIn: string; signIn: string; newClient: string; createAccount: string; registerEyebrow: string; registerTitle: string; registerDescription: string; fullName: string; whatsapp: string; company: string; confirmPassword: string; creating: string; existing: string };
  home: { eyebrow: string; title: string; description: string; primary: string; secondary: string; trust: string; searchPlaceholder: string; popular: string; valueEyebrow: string; valueTitle: string; servicesEyebrow: string; servicesTitle: string; processEyebrow: string; processTitle: string; processDescription: string; quoteEyebrow: string; quoteTitle: string; quoteDescription: string; finalTitle: string; finalDescription: string; noPayment: string };
  portal: { ownerWorkspace: string; clientPortal: string; overview: string; analytics: string; inquiries: string; services: string; quotations: string; projects: string; invoices: string; payments: string; reviews: string; settings: string; home: string; messages: string; profile: string };
  footer: { description: string; services: string; clients: string; company: string; copyright: string };
  portfolio: { eyebrow: string; title: string; description: string; externalTitle: string; externalDescription: string; externalCta: string; reviewsEyebrow: string; reviewsTitle: string; reviewsCta: string; emptyTitle: string; emptyDescription: string };
  about: { badge: string; title: string; intro: string; identityTitle: string; identity: string; approachTitle: string; approach: string; capabilityTitle: string; capability: string; collaborationTitle: string; collaboration: string; portfolioCta: string; servicesCta: string };
  dashboard: { ownerEyebrow: string; ownerTitle: string; ownerDescription: string; clientEyebrow: string; clientWelcome: string; clientDescription: string; noActiveProject: string; noActiveProjectDescription: string; exploreServices: string; startProject: string };
  analytics: { eyebrow: string; title: string; description: string; currentPeriod: string; previousPeriod: string; last7Days: string; last30Days: string; last90Days: string; yearToDate: string; inquiries: string; quotationsSent: string; acceptedQuotations: string; acceptedValue: string; cashReceived: string; activeClients: string; outstanding: string; operationalPipeline: string; funnelNote: string; quotationRate: string; acceptanceRate: string; projectRate: string; financialHealth: string; overdue: string; dueSoon: string; projectWorkload: string; awaiting: string; delivery: string; review: string; onHold: string; completed: string; attention: string; delayedInquiries: string; expiringQuotations: string; pendingProofs: string; clientReview: string; staleProjects: string; noAttention: string; noDataTitle: string; noDataDescription: string; viewDetails: string; noConversion: string; activeNow: string; includedArchives: string; days: string; };
  errors: { title: string; description: string; notFoundTitle: string; notFoundDescription: string; home: string };
};

const en: Dictionary = {
  nav: { services: "Services", portfolio: "Portfolio", process: "How It Works", reviews: "Reviews", about: "About", signIn: "Sign In", startProject: "Start a Project" },
  common: { search: "Search", viewAll: "View all", learnMore: "Learn more", back: "Back", save: "Save", loading: "Loading…", retry: "Try again", signOut: "Sign Out", notifications: "Notifications", noData: "No data yet", archive: "Archive", restore: "Restore", archived: "Archived", activeRecords: "Active records", archiveRecords: "Archived records", archivedAt: "Archived at", results: "results", clearFilters: "Clear filters", all: "All" },
  auth: { welcome: "Welcome back", loginTitle: "Sign in to your portal.", loginDescription: "Review quotations, track projects, manage invoices, and approve deliveries.", email: "Email", password: "Password", signingIn: "Signing in…", signIn: "Sign In", newClient: "New client?", createAccount: "Create an account", registerEyebrow: "Client account", registerTitle: "Manage every project in one place.", registerDescription: "Your account is used for quotations, agreements, projects, invoices, files, and reviews.", fullName: "Full name", whatsapp: "WhatsApp number", company: "Company (optional)", confirmPassword: "Confirm password", creating: "Creating account…", existing: "Already registered?" },
  home: { eyebrow: "Digital projects, managed clearly", title: "The right process for your next digital project.", description: "Explore professional services, discuss what you actually need, receive a clear quotation, and manage the work from the first brief to final delivery.", primary: "Start a Project", secondary: "Explore Services", trust: "Clear scope. Transparent workflow. Reliable delivery.", searchPlaceholder: "Search for a service", popular: "Popular:", valueEyebrow: "A better way to collaborate", valueTitle: "Professional services with a clearer way of working.", servicesEyebrow: "Selected expertise", servicesTitle: "Services shaped around the project.", processEyebrow: "How it works", processTitle: "A clear process from idea to completion.", processDescription: "No instant checkout and no hidden scope. Every project begins with context, discussion, and a quotation you can review.", quoteEyebrow: "Quotation-first workflow", quoteTitle: "Know the scope and cost before the work begins.", quoteDescription: "Every quotation documents deliverables, exclusions, timeline, revision limits, payment terms, and project total.", finalTitle: "Start your next project with a clearer process.", finalDescription: "Share the brief, discuss the real needs, and receive a quotation before committing to the work.", noPayment: "No payment is requested before the quotation and agreement are approved." },
  portal: { ownerWorkspace: "Owner workspace", clientPortal: "Client portal", overview: "Overview", analytics: "Analytics", inquiries: "Inquiries", services: "Services", quotations: "Quotations", projects: "Projects", invoices: "Invoices", payments: "Payments", reviews: "Reviews", settings: "Settings", home: "Home", messages: "Messages", profile: "Profile" },
  footer: { description: "Professional digital services with a clearer process—from the first brief to final delivery.", services: "Services", clients: "For Clients", company: "Company", copyright: "Built for transparent collaboration." },
  portfolio: { eyebrow: "Selected work", title: "Projects, decisions, and measurable outcomes.", description: "Selected work is presented here, while complete case studies and technical portfolio are available on the external portfolio site.", externalTitle: "View the complete professional portfolio", externalDescription: "Explore project stories, technical stack, and current work by Radhiansyah Putra.", externalCta: "Open portfolio", reviewsEyebrow: "Verified reviews", reviewsTitle: "Feedback tied to completed projects.", reviewsCta: "View all reviews", emptyTitle: "Case studies are being prepared", emptyDescription: "Published project stories will include context, process, technology, and outcomes." },
  about: { badge: "About RRS", title: "Digital products should be built with clarity, context, and accountable delivery.", intro: "RRS is an independent digital service practice led by Radhiansyah Putra, a Full-Stack Developer focused on practical, maintainable products.", identityTitle: "Professional identity", identity: "Radhiansyah Putra works across product thinking, interface design, and full-stack implementation to turn business needs into usable digital systems.", approachTitle: "Working approach", approach: "Each engagement begins with discovery and a clear scope, then moves through UI/UX design, implementation, review, and documented handover.", capabilityTitle: "Core capabilities", capability: "RRS supports business websites, web applications, client portals, operations dashboards, API integrations, data workflows, and AI-ready product foundations.", collaborationTitle: "Collaboration model", collaboration: "Available for remote collaboration from Bandung and Bekasi, Indonesia. Every project follows a quotation-first process so scope, timeline, revisions, and payment expectations are agreed before work begins.", portfolioCta: "View full portfolio", servicesCta: "Explore services" },
  dashboard: { ownerEyebrow: "Owner overview", ownerTitle: "Work that needs attention.", ownerDescription: "Monitor client requests, quotations, projects, and public services from one workspace.", clientEyebrow: "Client overview", clientWelcome: "Welcome", clientDescription: "Your accepted quotations, active projects, files, and invoices will appear here.", noActiveProject: "No active project yet", noActiveProjectDescription: "Start with a project brief. After discussion and quotation approval, your project workspace will be created automatically.", exploreServices: "Explore Services", startProject: "Share Project Brief" },
  analytics: { eyebrow: "Owner analytics", title: "Business health, without the noise.", description: "Track the delivery pipeline, current financial position, and work that needs action today.", currentPeriod: "Selected period", previousPeriod: "vs previous period", last7Days: "7 days", last30Days: "30 days", last90Days: "90 days", yearToDate: "Year to date", inquiries: "Inquiries received", quotationsSent: "Quotations sent", acceptedQuotations: "Quotations accepted", acceptedValue: "Accepted quotation value", cashReceived: "Cash received", activeClients: "Clients with active projects", outstanding: "Outstanding receivable", operationalPipeline: "Operational pipeline", funnelNote: "Counts are grouped by activity in the selected period.", quotationRate: "Inquiry to quotation", acceptanceRate: "Quotation acceptance", projectRate: "Accepted to project", financialHealth: "Financial health", overdue: "Overdue invoices", dueSoon: "Due in the next 7 days", projectWorkload: "Project workload", awaiting: "Awaiting agreement / payment", delivery: "Planning & in progress", review: "Client review & revision", onHold: "On hold", completed: "Completed", attention: "Needs attention", delayedInquiries: "Inquiries awaiting review", expiringQuotations: "Quotations expiring soon", pendingProofs: "Payment proofs awaiting verification", clientReview: "Projects in client review", staleProjects: "Projects without an update for 7 days", noAttention: "Nothing needs immediate attention.", noDataTitle: "Insights will appear as work starts moving.", noDataDescription: "Create an inquiry or quotation to begin building the operating picture for RRS.", viewDetails: "View details", noConversion: "No data", activeNow: "Current", includedArchives: "Archived inquiries and quotations remain included in business metrics.", days: "days" },
  errors: { title: "Something went wrong", description: "The requested content could not be loaded safely.", notFoundTitle: "Page not found", notFoundDescription: "The page may have moved or the link is no longer valid.", home: "Return home" },
};

const id: Dictionary = {
  nav: { services: "Layanan", portfolio: "Portofolio", process: "Cara Kerja", reviews: "Ulasan", about: "Tentang", signIn: "Masuk", startProject: "Mulai Proyek" },
  common: { search: "Cari", viewAll: "Lihat semua", learnMore: "Pelajari", back: "Kembali", save: "Simpan", loading: "Memuat…", retry: "Coba lagi", signOut: "Keluar", notifications: "Notifikasi", noData: "Belum ada data", archive: "Arsipkan", restore: "Pulihkan", archived: "Diarsipkan", activeRecords: "Data aktif", archiveRecords: "Data arsip", archivedAt: "Diarsipkan pada", results: "layanan ditemukan", clearFilters: "Hapus filter", all: "Semua" },
  auth: { welcome: "Selamat datang kembali", loginTitle: "Masuk ke portal Anda.", loginDescription: "Tinjau quotation, pantau proyek, kelola invoice, dan setujui hasil pekerjaan.", email: "Email", password: "Kata sandi", signingIn: "Sedang masuk…", signIn: "Masuk", newClient: "Client baru?", createAccount: "Buat akun", registerEyebrow: "Akun client", registerTitle: "Kelola setiap proyek di satu tempat.", registerDescription: "Akun digunakan untuk quotation, agreement, proyek, invoice, file, dan ulasan.", fullName: "Nama lengkap", whatsapp: "Nomor WhatsApp", company: "Perusahaan (opsional)", confirmPassword: "Konfirmasi kata sandi", creating: "Membuat akun…", existing: "Sudah terdaftar?" },
  home: { eyebrow: "Proyek digital, dikelola dengan jelas", title: "Proses yang tepat untuk proyek digital Anda.", description: "Jelajahi layanan profesional, diskusikan kebutuhan sebenarnya, terima quotation yang jelas, dan kelola pekerjaan dari brief hingga hasil akhir.", primary: "Mulai Proyek", secondary: "Jelajahi Layanan", trust: "Scope jelas. Alur transparan. Hasil dapat diandalkan.", searchPlaceholder: "Cari layanan", popular: "Populer:", valueEyebrow: "Cara kolaborasi yang lebih baik", valueTitle: "Layanan profesional dengan cara kerja yang lebih jelas.", servicesEyebrow: "Keahlian pilihan", servicesTitle: "Layanan yang disesuaikan dengan proyek.", processEyebrow: "Cara kerja", processTitle: "Proses jelas dari ide hingga selesai.", processDescription: "Tanpa checkout instan dan tanpa scope tersembunyi. Setiap proyek dimulai dari konteks, diskusi, dan quotation yang dapat Anda tinjau.", quoteEyebrow: "Alur berbasis quotation", quoteTitle: "Ketahui scope dan biaya sebelum pekerjaan dimulai.", quoteDescription: "Setiap quotation mencatat deliverables, pengecualian, timeline, batas revisi, pembayaran, dan total proyek.", finalTitle: "Mulai proyek berikutnya dengan proses yang lebih jelas.", finalDescription: "Kirim brief, diskusikan kebutuhan nyata, dan terima quotation sebelum menyetujui pekerjaan.", noPayment: "Tidak ada pembayaran sebelum quotation dan agreement disetujui." },
  portal: { ownerWorkspace: "Workspace owner", clientPortal: "Portal client", overview: "Ringkasan", analytics: "Analitik", inquiries: "Inquiry", services: "Layanan", quotations: "Quotation", projects: "Proyek", invoices: "Invoice", payments: "Pembayaran", reviews: "Ulasan", settings: "Pengaturan", home: "Beranda", messages: "Pesan", profile: "Profil" },
  footer: { description: "Layanan digital profesional dengan proses yang lebih jelas—dari brief pertama hingga hasil akhir.", services: "Layanan", clients: "Untuk Client", company: "Perusahaan", copyright: "Dibangun untuk kolaborasi yang transparan." },
  portfolio: { eyebrow: "Karya pilihan", title: "Project, keputusan, dan hasil yang dapat dipertanggungjawabkan.", description: "Ringkasan karya ditampilkan di sini, sementara case study lengkap dan portofolio teknis tersedia pada situs portofolio eksternal.", externalTitle: "Lihat portofolio profesional lengkap", externalDescription: "Jelajahi cerita project, technical stack, dan karya terkini Radhiansyah Putra.", externalCta: "Buka portofolio", reviewsEyebrow: "Ulasan terverifikasi", reviewsTitle: "Feedback dari project yang telah selesai.", reviewsCta: "Lihat semua ulasan", emptyTitle: "Case study sedang disiapkan", emptyDescription: "Cerita project yang dipublikasikan akan memuat konteks, proses, teknologi, dan hasil." },
  about: { badge: "Tentang RRS", title: "Produk digital perlu dibangun dengan kejelasan, konteks, dan delivery yang dapat dipertanggungjawabkan.", intro: "RRS adalah praktik layanan digital independen yang dipimpin oleh Radhiansyah Putra, seorang Full-Stack Developer yang berfokus pada produk praktis dan mudah dikembangkan.", identityTitle: "Identitas profesional", identity: "Radhiansyah Putra bekerja pada product thinking, desain antarmuka, dan implementasi full-stack untuk mengubah kebutuhan bisnis menjadi sistem digital yang mudah digunakan.", approachTitle: "Cara kerja", approach: "Setiap engagement dimulai dari discovery dan scope yang jelas, lalu berlanjut ke UI/UX design, implementasi, review, dan handover yang terdokumentasi.", capabilityTitle: "Kemampuan utama", capability: "RRS mendukung website bisnis, web application, client portal, operations dashboard, integrasi API, workflow data, serta fondasi produk yang AI-ready.", collaborationTitle: "Model kolaborasi", collaboration: "Tersedia untuk kolaborasi remote dari Bandung dan Bekasi, Indonesia. Setiap project menggunakan proses quotation-first agar scope, timeline, revisi, dan pembayaran disepakati sebelum pekerjaan dimulai.", portfolioCta: "Lihat portofolio lengkap", servicesCta: "Jelajahi layanan" },
  dashboard: { ownerEyebrow: "Ringkasan owner", ownerTitle: "Pekerjaan yang perlu diperhatikan.", ownerDescription: "Pantau permintaan client, quotation, proyek, dan layanan publik dari satu workspace.", clientEyebrow: "Ringkasan client", clientWelcome: "Selamat datang", clientDescription: "Quotation yang diterima, proyek aktif, file, dan invoice Anda akan tampil di sini.", noActiveProject: "Belum ada proyek aktif", noActiveProjectDescription: "Mulai dari project brief. Setelah diskusi dan quotation disetujui, workspace proyek akan dibuat secara otomatis.", exploreServices: "Pilih Layanan", startProject: "Mulai Project Brief" },
  analytics: { eyebrow: "Analitik owner", title: "Kesehatan bisnis, tanpa informasi yang berisik.", description: "Pantau pipeline delivery, posisi keuangan saat ini, serta pekerjaan yang perlu ditindak hari ini.", currentPeriod: "Periode dipilih", previousPeriod: "vs periode sebelumnya", last7Days: "7 hari", last30Days: "30 hari", last90Days: "90 hari", yearToDate: "Tahun berjalan", inquiries: "Inquiry masuk", quotationsSent: "Quotation terkirim", acceptedQuotations: "Quotation diterima", acceptedValue: "Nilai quotation diterima", cashReceived: "Kas diterima", activeClients: "Client dengan proyek aktif", outstanding: "Piutang berjalan", operationalPipeline: "Pipeline operasional", funnelNote: "Jumlah dihitung dari aktivitas pada periode yang dipilih.", quotationRate: "Inquiry ke quotation", acceptanceRate: "Quotation diterima", projectRate: "Diterima ke proyek", financialHealth: "Kesehatan keuangan", overdue: "Invoice terlambat", dueSoon: "Jatuh tempo 7 hari ke depan", projectWorkload: "Beban proyek", awaiting: "Menunggu agreement / pembayaran", delivery: "Perencanaan & pengerjaan", review: "Review client & revisi", onHold: "Ditunda", completed: "Selesai", attention: "Perlu perhatian", delayedInquiries: "Inquiry menunggu ditinjau", expiringQuotations: "Quotation segera kedaluwarsa", pendingProofs: "Bukti bayar menunggu verifikasi", clientReview: "Proyek dalam review client", staleProjects: "Proyek tanpa pembaruan 7 hari", noAttention: "Tidak ada hal yang perlu segera ditindak.", noDataTitle: "Insight akan muncul saat pekerjaan mulai berjalan.", noDataDescription: "Buat inquiry atau quotation untuk mulai membangun gambaran operasional RRS.", viewDetails: "Lihat detail", noConversion: "Belum ada data", activeNow: "Saat ini", includedArchives: "Inquiry dan quotation yang diarsipkan tetap dihitung pada metric bisnis.", days: "hari" },
  errors: { title: "Terjadi kesalahan", description: "Konten yang diminta tidak dapat dimuat dengan aman.", notFoundTitle: "Halaman tidak ditemukan", notFoundDescription: "Halaman mungkin telah dipindahkan atau tautan sudah tidak berlaku.", home: "Kembali ke beranda" },
};

const dictionaries: Record<Locale, Dictionary> = { id, en };
export function getDictionary(locale: Locale) { return dictionaries[locale]; }

const statusId: Record<string, string> = {
  DRAFT: "Draf", SUBMITTED: "Terkirim", REVIEWING: "Ditinjau", DISCUSSING: "Diskusi", WAITING_FOR_CLIENT: "Menunggu client", READY_FOR_QUOTATION: "Siap dibuatkan quotation", QUOTATION_SENT: "Quotation terkirim", SENT: "Terkirim", VIEWED: "Dilihat", REVISION_REQUESTED: "Revisi diminta", ACCEPTED: "Diterima", REJECTED: "Ditolak", EXPIRED: "Kedaluwarsa", CANCELLED: "Dibatalkan", ARCHIVED: "Diarsipkan", AWAITING_AGREEMENT: "Menunggu agreement", AWAITING_DOWN_PAYMENT: "Menunggu pembayaran awal", PLANNING: "Perencanaan", IN_PROGRESS: "Dikerjakan", CLIENT_REVIEW: "Ditinjau client", REVISION: "Revisi", ON_HOLD: "Ditunda", COMPLETED: "Selesai", ISSUED: "Diterbitkan", PENDING: "Menunggu", PARTIALLY_PAID: "Dibayar sebagian", PAID: "Lunas", OVERDUE: "Terlambat", VOID: "Dibatalkan", REFUNDED: "Dikembalikan", UNDER_VERIFICATION: "Sedang diverifikasi", VERIFIED: "Terverifikasi", FAILED: "Gagal", PROCESSING: "Diproses", PUBLISHED: "Dipublikasikan", HIDDEN: "Disembunyikan" };
export function statusLabel(locale: Locale, status: string) {
  return locale === "id" ? statusId[status] ?? status.replaceAll("_", " ") : status.replaceAll("_", " ");
}
