import type { Locale } from "@/i18n/config";

type Dictionary = {
  nav: { services: string; portfolio: string; process: string; reviews: string; about: string; signIn: string; startProject: string };
  common: { search: string; viewAll: string; learnMore: string; back: string; save: string; loading: string; retry: string; signOut: string; notifications: string; noData: string };
  auth: { welcome: string; loginTitle: string; loginDescription: string; email: string; password: string; signingIn: string; signIn: string; newClient: string; createAccount: string; registerEyebrow: string; registerTitle: string; registerDescription: string; fullName: string; whatsapp: string; company: string; confirmPassword: string; creating: string; existing: string };
  home: { eyebrow: string; title: string; description: string; primary: string; secondary: string; trust: string; searchPlaceholder: string; popular: string; valueEyebrow: string; valueTitle: string; servicesEyebrow: string; servicesTitle: string; processEyebrow: string; processTitle: string; processDescription: string; quoteEyebrow: string; quoteTitle: string; quoteDescription: string; finalTitle: string; finalDescription: string; noPayment: string };
  portal: { ownerWorkspace: string; clientPortal: string; overview: string; inquiries: string; quotations: string; projects: string; invoices: string; payments: string; reviews: string; settings: string; home: string; messages: string; profile: string };
  footer: { description: string; services: string; clients: string; company: string; copyright: string };
  errors: { title: string; description: string; notFoundTitle: string; notFoundDescription: string; home: string };
};

const en: Dictionary = {
  nav: { services: "Services", portfolio: "Portfolio", process: "How It Works", reviews: "Reviews", about: "About", signIn: "Sign In", startProject: "Start a Project" },
  common: { search: "Search", viewAll: "View all", learnMore: "Learn more", back: "Back", save: "Save", loading: "Loading…", retry: "Try again", signOut: "Sign Out", notifications: "Notifications", noData: "No data yet" },
  auth: { welcome: "Welcome back", loginTitle: "Sign in to your portal.", loginDescription: "Review quotations, track projects, manage invoices, and approve deliveries.", email: "Email", password: "Password", signingIn: "Signing in…", signIn: "Sign In", newClient: "New client?", createAccount: "Create an account", registerEyebrow: "Client account", registerTitle: "Manage every project in one place.", registerDescription: "Your account is used for quotations, agreements, projects, invoices, files, and reviews.", fullName: "Full name", whatsapp: "WhatsApp number", company: "Company (optional)", confirmPassword: "Confirm password", creating: "Creating account…", existing: "Already registered?" },
  home: { eyebrow: "Digital projects, managed clearly", title: "The right process for your next digital project.", description: "Explore professional services, discuss what you actually need, receive a clear quotation, and manage the work from the first brief to final delivery.", primary: "Start a Project", secondary: "Explore Services", trust: "Clear scope. Transparent workflow. Reliable delivery.", searchPlaceholder: "Search for a service", popular: "Popular:", valueEyebrow: "A better way to collaborate", valueTitle: "Professional services with a clearer way of working.", servicesEyebrow: "Selected expertise", servicesTitle: "Services shaped around the project.", processEyebrow: "How it works", processTitle: "A clear process from idea to completion.", processDescription: "No instant checkout and no hidden scope. Every project begins with context, discussion, and a quotation you can review.", quoteEyebrow: "Quotation-first workflow", quoteTitle: "Know the scope and cost before the work begins.", quoteDescription: "Every quotation documents deliverables, exclusions, timeline, revision limits, payment terms, and project total.", finalTitle: "Start your next project with a clearer process.", finalDescription: "Share the brief, discuss the real needs, and receive a quotation before committing to the work.", noPayment: "No payment is requested before the quotation and agreement are approved." },
  portal: { ownerWorkspace: "Owner workspace", clientPortal: "Client portal", overview: "Overview", inquiries: "Inquiries", quotations: "Quotations", projects: "Projects", invoices: "Invoices", payments: "Payments", reviews: "Reviews", settings: "Settings", home: "Home", messages: "Messages", profile: "Profile" },
  footer: { description: "Professional digital services with a clearer process—from the first brief to final delivery.", services: "Services", clients: "For Clients", company: "Company", copyright: "Built for transparent collaboration." },
  errors: { title: "Something went wrong", description: "The requested content could not be loaded safely.", notFoundTitle: "Page not found", notFoundDescription: "The page may have moved or the link is no longer valid.", home: "Return home" },
};

const id: Dictionary = {
  nav: { services: "Layanan", portfolio: "Portofolio", process: "Cara Kerja", reviews: "Ulasan", about: "Tentang", signIn: "Masuk", startProject: "Mulai Proyek" },
  common: { search: "Cari", viewAll: "Lihat semua", learnMore: "Pelajari", back: "Kembali", save: "Simpan", loading: "Memuat…", retry: "Coba lagi", signOut: "Keluar", notifications: "Notifikasi", noData: "Belum ada data" },
  auth: { welcome: "Selamat datang kembali", loginTitle: "Masuk ke portal Anda.", loginDescription: "Tinjau quotation, pantau proyek, kelola invoice, dan setujui hasil pekerjaan.", email: "Email", password: "Kata sandi", signingIn: "Sedang masuk…", signIn: "Masuk", newClient: "Client baru?", createAccount: "Buat akun", registerEyebrow: "Akun client", registerTitle: "Kelola setiap proyek di satu tempat.", registerDescription: "Akun digunakan untuk quotation, agreement, proyek, invoice, file, dan ulasan.", fullName: "Nama lengkap", whatsapp: "Nomor WhatsApp", company: "Perusahaan (opsional)", confirmPassword: "Konfirmasi kata sandi", creating: "Membuat akun…", existing: "Sudah terdaftar?" },
  home: { eyebrow: "Proyek digital, dikelola dengan jelas", title: "Proses yang tepat untuk proyek digital Anda.", description: "Jelajahi layanan profesional, diskusikan kebutuhan sebenarnya, terima quotation yang jelas, dan kelola pekerjaan dari brief hingga hasil akhir.", primary: "Mulai Proyek", secondary: "Jelajahi Layanan", trust: "Scope jelas. Alur transparan. Hasil dapat diandalkan.", searchPlaceholder: "Cari layanan", popular: "Populer:", valueEyebrow: "Cara kolaborasi yang lebih baik", valueTitle: "Layanan profesional dengan cara kerja yang lebih jelas.", servicesEyebrow: "Keahlian pilihan", servicesTitle: "Layanan yang disesuaikan dengan proyek.", processEyebrow: "Cara kerja", processTitle: "Proses jelas dari ide hingga selesai.", processDescription: "Tanpa checkout instan dan tanpa scope tersembunyi. Setiap proyek dimulai dari konteks, diskusi, dan quotation yang dapat Anda tinjau.", quoteEyebrow: "Alur berbasis quotation", quoteTitle: "Ketahui scope dan biaya sebelum pekerjaan dimulai.", quoteDescription: "Setiap quotation mencatat deliverables, pengecualian, timeline, batas revisi, pembayaran, dan total proyek.", finalTitle: "Mulai proyek berikutnya dengan proses yang lebih jelas.", finalDescription: "Kirim brief, diskusikan kebutuhan nyata, dan terima quotation sebelum menyetujui pekerjaan.", noPayment: "Tidak ada pembayaran sebelum quotation dan agreement disetujui." },
  portal: { ownerWorkspace: "Workspace owner", clientPortal: "Portal client", overview: "Ringkasan", inquiries: "Inquiry", quotations: "Quotation", projects: "Proyek", invoices: "Invoice", payments: "Pembayaran", reviews: "Ulasan", settings: "Pengaturan", home: "Beranda", messages: "Pesan", profile: "Profil" },
  footer: { description: "Layanan digital profesional dengan proses yang lebih jelas—dari brief pertama hingga hasil akhir.", services: "Layanan", clients: "Untuk Client", company: "Perusahaan", copyright: "Dibangun untuk kolaborasi yang transparan." },
  errors: { title: "Terjadi kesalahan", description: "Konten yang diminta tidak dapat dimuat dengan aman.", notFoundTitle: "Halaman tidak ditemukan", notFoundDescription: "Halaman mungkin telah dipindahkan atau tautan sudah tidak berlaku.", home: "Kembali ke beranda" },
};

const dictionaries: Record<Locale, Dictionary> = { id, en };
export function getDictionary(locale: Locale) { return dictionaries[locale]; }

const statusId: Record<string, string> = {
  DRAFT: "Draf", SUBMITTED: "Terkirim", REVIEWING: "Ditinjau", DISCUSSING: "Diskusi", WAITING_FOR_CLIENT: "Menunggu client", READY_FOR_QUOTATION: "Siap dibuatkan quotation", QUOTATION_SENT: "Quotation terkirim", SENT: "Terkirim", VIEWED: "Dilihat", REVISION_REQUESTED: "Revisi diminta", ACCEPTED: "Diterima", REJECTED: "Ditolak", EXPIRED: "Kedaluwarsa", CANCELLED: "Dibatalkan", ARCHIVED: "Diarsipkan", AWAITING_AGREEMENT: "Menunggu agreement", AWAITING_DOWN_PAYMENT: "Menunggu pembayaran awal", PLANNING: "Perencanaan", IN_PROGRESS: "Dikerjakan", CLIENT_REVIEW: "Ditinjau client", REVISION: "Revisi", ON_HOLD: "Ditunda", COMPLETED: "Selesai", ISSUED: "Diterbitkan", PENDING: "Menunggu", PARTIALLY_PAID: "Dibayar sebagian", PAID: "Lunas", OVERDUE: "Terlambat", VOID: "Dibatalkan", REFUNDED: "Dikembalikan", UNDER_VERIFICATION: "Sedang diverifikasi", VERIFIED: "Terverifikasi", FAILED: "Gagal", PROCESSING: "Diproses", PUBLISHED: "Dipublikasikan", HIDDEN: "Disembunyikan" };
export function statusLabel(locale: Locale, status: string) {
  return locale === "id" ? statusId[status] ?? status.replaceAll("_", " ") : status.replaceAll("_", " ");
}
