import Link from "next/link";
import { FileText } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PaginationControls, pageSize, parsePage } from "@/components/ui/pagination-controls";
import { requireClient } from "@/lib/authz";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";
export const dynamic="force-dynamic";
export default async function ClientQuotationsPage({searchParams}:{searchParams:Promise<{page?:string}>}){const [user,{page:rawPage}]=await Promise.all([requireClient(),searchParams]);const page=parsePage(rawPage);const rows=await prisma.quotation.findMany({where:{isCurrent:true,OR:[{clientId:user.id},{clientEmail:user.email??undefined}]},orderBy:{updatedAt:"desc"},skip:(page-1)*pageSize,take:pageSize+1,select:{id:true,projectTitle:true,quotationNumber:true,version:true,validUntil:true,total:true,status:true}});const hasNext=rows.length>pageSize;const quotes=rows.slice(0,pageSize);return <><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Quotations</p><h1 className="mt-3 font-display text-3xl font-extrabold">Commercial documents for your projects.</h1>{quotes.length===0&&page===1?<EmptyState className="mt-8" icon={FileText} title="No linked quotations" description="A quotation becomes linked to your account after the matching client email is used or the document is accepted."/>:<><div className="mt-8 grid gap-4">{quotes.map((quote)=><Link key={quote.id} href={`/client/quotations/${quote.id}`}><Card className="transition-all hover:-translate-y-0.5 hover:shadow-md"><CardContent className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="font-display text-lg font-extrabold">{quote.projectTitle}</p><p className="mt-1 text-xs text-secondary">{quote.quotationNumber} v{quote.version} · valid until {quote.validUntil.toLocaleDateString("id-ID")}</p></div><div className="flex items-center gap-4"><p className="font-display text-lg font-extrabold text-primary">{formatIdr(quote.total.toString())}</p><Badge>{quote.status.replaceAll("_"," ")}</Badge></div></CardContent></Card></Link>)}</div><PaginationControls pathname="/client/quotations" page={page} hasNext={hasNext}/></>}</>}
