"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { z } from "zod";
import { MilestoneStatus, ProjectStatus } from "@/generated/prisma/enums";
import { requireOwner, requireUser } from "@/lib/authz";
import { prisma } from "@/lib/db/prisma";
import { projectWorkflow } from "@/features/workflow/transitions";
import { generatePublicToken, hashPublicToken } from "@/lib/security/tokens";
import { storePrivateFile, removePrivateFile, type StoredFile } from "@/lib/storage/local";

export async function acceptAgreementAction(formData:FormData){const user=await requireUser();const data=z.object({projectId:z.string(),agreementVersion:z.coerce.number().int().positive(),acceptTerms:z.literal("on")}).parse(Object.fromEntries(formData));const requestHeaders=await headers();const forwardedFor=requestHeaders.get("x-forwarded-for");const acceptanceIp=forwardedFor?.split(",")[0]?.trim()??requestHeaders.get("x-real-ip");const acceptanceAgent=requestHeaders.get("user-agent");await prisma.$transaction(async(tx)=>{const project=await tx.project.findFirst({where:{id:data.projectId,clientId:user.id},include:{agreement:true}});if(!project?.agreement||project.status!=="AWAITING_AGREEMENT"||project.agreement.status!=="PENDING"||project.agreement.version!==data.agreementVersion)throw new Error("Agreement cannot be accepted.");await tx.agreement.update({where:{id:project.agreement.id},data:{status:"ACCEPTED",acceptedByName:user.name??"Client",acceptedByEmail:user.email,acceptedAt:new Date(),acceptanceIp,acceptanceAgent}});await tx.project.update({where:{id:project.id},data:{status:"AWAITING_DOWN_PAYMENT",activities:{create:{type:"AGREEMENT_ACCEPTED",description:`Client accepted agreement ${project.agreement.agreementNumber} v${project.agreement.version}.`}}}});});revalidatePath(`/client/projects/${data.projectId}`);revalidatePath(`/client/projects/${data.projectId}/agreement`);revalidatePath(`/owner/projects/${data.projectId}`);revalidatePath(`/owner/projects/${data.projectId}/agreement`);revalidatePath("/owner/analytics");redirect(`/client/projects/${data.projectId}/agreement?accepted=1`)}

export async function updateProjectStatusAction(formData:FormData){await requireOwner();const projectId=z.string().parse(formData.get("projectId"));const next=z.enum(ProjectStatus).parse(formData.get("status"));await prisma.$transaction(async(tx)=>{const project=await tx.project.findUniqueOrThrow({where:{id:projectId}});if(next==="COMPLETED")throw new Error("Project completion requires client delivery approval.");if(!projectWorkflow.canTransition(project.status,next))throw new Error(`Invalid project transition: ${project.status} → ${next}`);if(project.status==="AWAITING_DOWN_PAYMENT"&&next==="PLANNING"){const paidInvoice=await tx.invoice.findFirst({where:{projectId:project.id,status:"PAID"},select:{id:true}});if(!paidInvoice)throw new Error("The required first invoice must be paid before planning begins.");}await tx.project.update({where:{id:project.id},data:{status:next,activities:{create:{type:"STATUS_UPDATED",description:`Project moved from ${project.status} to ${next}.`}}}});});redirect(`/owner/projects/${projectId}`)}

export async function approveProjectDeliveryAction(formData:FormData){const user=await requireUser();const projectId=z.string().parse(formData.get("projectId"));const token=generatePublicToken();await prisma.$transaction(async(tx)=>{const project=await tx.project.findFirst({where:{id:projectId,clientId:user.id},include:{milestones:true}});if(!project||project.status!=="CLIENT_REVIEW")throw new Error("Project is not waiting for client approval.");const incomplete=project.milestones.some((milestone)=>!["APPROVED","COMPLETED"].includes(milestone.status));if(incomplete)throw new Error("All milestones must be approved or completed before final delivery approval.");await tx.project.update({where:{id:project.id},data:{status:"COMPLETED",completedAt:new Date(),activities:{create:{type:"DELIVERY_APPROVED",description:"Client approved final delivery and completed the project."}}}});await tx.reviewInvitation.upsert({where:{projectId:project.id},update:{tokenHash:hashPublicToken(token),expiresAt:new Date(Date.now()+30*24*60*60*1000),revokedAt:null,usedAt:null},create:{projectId:project.id,tokenHash:hashPublicToken(token),expiresAt:new Date(Date.now()+30*24*60*60*1000)}});});redirect(`/review/${token}`)}

export async function createMilestoneAction(formData:FormData){await requireOwner();const data=z.object({projectId:z.string(),title:z.string().trim().min(2).max(160),description:z.string().trim().max(3000).optional(),dueDate:z.string().optional()}).parse(Object.fromEntries(formData));const last=await prisma.projectMilestone.aggregate({where:{projectId:data.projectId},_max:{sequence:true}});await prisma.projectMilestone.create({data:{projectId:data.projectId,title:data.title,description:data.description||null,dueDate:data.dueDate?new Date(`${data.dueDate}T12:00:00+07:00`):null,sequence:(last._max.sequence??0)+1}});revalidatePath(`/owner/projects/${data.projectId}`)}

export async function updateMilestoneAction(formData:FormData){await requireOwner();const data=z.object({milestoneId:z.string(),projectId:z.string(),status:z.enum(MilestoneStatus)}).parse(Object.fromEntries(formData));await prisma.projectMilestone.update({where:{id:data.milestoneId,projectId:data.projectId},data:{status:data.status,completedAt:data.status==="COMPLETED"?new Date():null}});revalidatePath(`/owner/projects/${data.projectId}`)}

export async function sendProjectMessageAction(formData:FormData){const user=await requireUser();const data=z.object({projectId:z.string(),message:z.string().trim().min(1).max(5000),returnTo:z.string().startsWith("/")}).parse(Object.fromEntries(formData));const project=await prisma.project.findUniqueOrThrow({where:{id:data.projectId},select:{clientId:true}});if(user.role!=="OWNER"&&project.clientId!==user.id)throw new Error("Project access denied.");await prisma.projectMessage.create({data:{projectId:data.projectId,senderId:user.id,message:data.message}});revalidatePath(data.returnTo)}

export async function uploadProjectFileAction(formData:FormData){const user=await requireUser();const projectId=z.string().parse(formData.get("projectId"));const returnTo=z.string().startsWith("/").parse(formData.get("returnTo"));const requestedType=z.enum(["REFERENCE","PROJECT_FILE","DELIVERY","REVISION","OTHER"]).parse(formData.get("type"));const project=await prisma.project.findUniqueOrThrow({where:{id:projectId},select:{clientId:true}});if(user.role!=="OWNER"&&project.clientId!==user.id)throw new Error("Project access denied.");if(user.role!=="OWNER"&&!["REFERENCE","REVISION","OTHER"].includes(requestedType))throw new Error("Clients cannot upload this file type.");const file=formData.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Choose a file to upload.");let stored:StoredFile|undefined;try{stored=await storePrivateFile(file,`projects/${projectId}`);await prisma.fileAsset.create({data:{projectId,uploaderId:user.id,type:requestedType,...stored}});revalidatePath(returnTo)}catch(error){if(stored)await removePrivateFile(stored.storageKey);throw error}}
