import Link from "next/link";
import { BriefcaseBusiness, Eye, EyeOff, Pencil, Plus, Search, Star } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { PaginationControls, pageSize, parsePage } from "@/components/ui/pagination-controls";
import { WorkspaceModule } from "@/components/workspace/workspace-module";
import { WorkspacePageHeader } from "@/components/workspace/workspace-page-header";
import { importDefaultServiceCatalogAction, importServicesThreeCatalogAction, restoreArchivedServiceAction, revertCatalogImportAction } from "@/features/services/actions";
import { previewServicesThreeCatalog, type ServicesThreeImportPreview } from "@/features/services/services-iii-catalog-import";
import { previewCatalogImportRevert, previewLegacyCatalogRevert, type CatalogRevertPreview } from "@/features/services/catalog-import-revert-preview";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function OwnerServicesPage({ searchParams }: { searchParams: Promise<{ page?: string; q?: string; type?: string; archive?: string; catalog?: string; preset?: string; preview?: string; run?: string; legacy?: string; reverted?: string; archived?: string; restored?: string; types?: string; services?: string; levels?: string; created?: string; updated?: string; skipped?: string; levelsCreated?: string; levelsUpdated?: string; levelsSkipped?: string }> }) {
  const { page: rawPage, q: rawQuery, type: rawType, archive, catalog, preset, preview, run, legacy, reverted, archived, restored, types: importedTypes, services: importedServices, levels: importedLevels, created, updated, skipped, levelsCreated, levelsUpdated, levelsSkipped } = await searchParams;
  const page = parsePage(rawPage);
  const q = rawQuery?.trim() ?? "";
  const archiveMode = archive === "1";
  const [selectedType, servicesThreePreview, trackedRevertPreview, legacyRevertPreview] = await Promise.all([
    rawType ? prisma.serviceType.findUnique({ where: { slug: rawType }, select: { id: true, name: true, slug: true, isActive: true } }) : null,
    preview === "services-three" ? previewServicesThreeCatalog(prisma) : null,
    run ? previewCatalogImportRevert(prisma, run) : null,
    legacy === "default" ? previewLegacyCatalogRevert(prisma, "DEFAULT_CATALOG") : legacy === "services-three" ? previewLegacyCatalogRevert(prisma, "SERVICES_III") : null,
  ]);
  const revertPreview = trackedRevertPreview ?? legacyRevertPreview;
  const filter = { archivedAt: archiveMode ? { not: null } : null, ...(selectedType ? { serviceTypeId: selectedType.id } : {}), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { slug: { contains: q, mode: "insensitive" as const } }, { category: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const [rows, total, published] = await Promise.all([
    prisma.service.findMany({ where: filter, orderBy: [{ isPublished: "asc" }, { category: "asc" }, { title: "asc" }], skip: (page - 1) * pageSize, take: pageSize + 1, select: { id: true, isPublished: true, isFeatured: true, catalogKind: true, showInPricingGuide: true, title: true, category: true, startingPrice: true, summary: true, updatedAt: true, archivedAt: true, _count: { select: { complexityLevels: true } } } }),
    prisma.service.count({ where: { archivedAt: null } }),
    prisma.service.count({ where: { archivedAt: null, isPublished: true } }),
  ]);
  const hasNext = rows.length > pageSize;
  const services = rows.slice(0, pageSize);

  return <>
    <WorkspacePageHeader eyebrow="Layanan" title="Kelola katalog yang ditampilkan ke Client." description="Draf tidak tampil di halaman publik. Unpublish mempertahankan riwayat quotation dan inquiry tanpa menghapus relasinya." actions={<><form className="relative w-full sm:w-72">{selectedType ? <input type="hidden" name="type" value={selectedType.slug} /> : null}<Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-secondary" aria-hidden="true"/><Input name="q" defaultValue={q} placeholder="Cari layanan atau kategori" aria-label="Cari layanan" className="pl-10"/></form><form action={importDefaultServiceCatalogAction}><Button type="submit" variant="outline">Impor katalog default</Button></form><Button asChild variant="outline"><Link href="/owner/services?preview=services-three">Preview preset Services III</Link></Button><Button asChild variant="outline"><Link href={archiveMode ? "/owner/services" : "/owner/services?archive=1"}>{archiveMode ? "Katalog aktif" : "Arsip layanan"}</Link></Button><Button asChild variant="outline"><Link href="/owner/services/types">Jenis layanan</Link></Button><Button asChild><Link href={selectedType?.isActive ? `/owner/services/create?type=${encodeURIComponent(selectedType.slug)}` : "/owner/services/create"}><Plus className="size-4" aria-hidden="true"/>{selectedType?.isActive ? `Buat layanan di ${selectedType.name}` : "Buat layanan"}</Link></Button></>}/>
    {catalog === "imported" ? <p role="status" className="mt-6 rounded-[10px] bg-accent-soft px-4 py-3 text-sm font-semibold text-primary">Katalog default diperiksa: {importedTypes ?? "0"} jenis, {importedServices ?? "0"} layanan, dan {importedLevels ?? "0"} level baru ditambahkan; {skipped ?? "0"} layanan existing tidak diubah.</p> : null}
    {preset === "services-three" ? <p role="status" className="mt-6 rounded-[10px] bg-accent-soft px-4 py-3 text-sm font-semibold text-primary">Preset Services III selesai: {created ?? "0"} layanan draft baru, {updated ?? "0"} layanan draft diperbarui, {levelsCreated ?? "0"} level baru, dan {levelsUpdated ?? "0"} level draft diperbarui. {skipped ?? "0"} layanan historis/published serta {levelsSkipped ?? "0"} level published tidak diubah.</p> : null}
    {servicesThreePreview ? <ServicesThreePreview preview={servicesThreePreview} /> : null}
    {reverted ? <p role="status" className="mt-6 rounded-[10px] bg-accent-soft px-4 py-3 text-sm font-semibold text-primary">{Number(archived ?? 0) + Number(restored ?? 0) > 0 ? `Revert import selesai: ${archived ?? "0"} draft diarsipkan dan ${restored ?? "0"} draft dipulihkan. Record terlindungi tetap tidak diubah.` : "Tidak ada draft yang dapat diubah oleh revert ini. Run tersebut tidak membuat perubahan katalog, atau semua record sudah dilindungi/berubah setelah import."}</p> : null}
    {revertPreview ? <CatalogRevertPreview preview={revertPreview} /> : null}
    <dl className="mt-8 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-3">
      <Metric label="Total layanan" value={total}/><Metric label="Sudah dipublikasikan" value={published}/><Metric label="Draf / belum tayang" value={total-published}/>
    </dl>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-[14px] border border-border bg-surface-container/40 px-4 py-3 text-sm"><p className="text-secondary">Butuh membalik draft dari import lama? Preview terlebih dahulu sebelum mengarsipkan record yang cocok.</p><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><Link href="/owner/services?legacy=default">Preview legacy katalog default</Link></Button><Button asChild size="sm" variant="outline"><Link href="/owner/services?legacy=services-three">Preview legacy Services III</Link></Button></div></div>
    {selectedType ? <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-[14px] border border-primary/20 bg-accent-soft/50 px-4 py-3 text-sm"><p><span className="font-semibold">Jenis aktif:</span> {selectedType.name}{q ? ` · Pencarian: “${q}”` : ""}</p><Button asChild size="sm" variant="outline"><Link href="/owner/services">Tampilkan semua layanan</Link></Button></div> : null}
    {services.length === 0 ? <EmptyState className="mt-8" icon={BriefcaseBusiness} title={page > 1 ? "Tidak ada layanan di halaman ini" : selectedType ? `Belum ada layanan di ${selectedType.name}` : "Belum ada layanan"} description={page > 1 ? "Kembali ke halaman pertama untuk melihat record layanan." : selectedType?.isActive ? `Buat layanan pertama yang langsung masuk ke jenis ${selectedType.name}.` : "Buat layanan pertama atau jalankan seed untuk memuat referensi layanan."}/> : <div className="mt-8 grid gap-5 lg:grid-cols-2">{services.map((service) => <WorkspaceModule key={service.id} titleId={`service-${service.id}`}><div className="p-5 md:p-6"><div className="flex justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap gap-2"><Badge variant={service.isPublished ? "success" : "neutral"}>{service.isPublished ? "Published" : "Draft"}</Badge>{service.catalogKind === "MICRO_TASK" && <Badge variant="warning">Micro Task</Badge>}{service.showInPricingGuide && <Badge>Project Fit Guide</Badge>}{service.isFeatured && <Badge><Star className="size-3" aria-hidden="true"/>Unggulan</Badge>}{service.archivedAt && <Badge variant="warning">Diarsipkan</Badge>}</div><h2 id={`service-${service.id}`} className="mt-4 font-display text-xl font-extrabold">{service.title}</h2><p className="mt-2 text-sm text-secondary">{service.category} · {service.startingPrice ? `Mulai dari ${formatIdr(service.startingPrice.toString())}` : "Custom scope"}</p><p className="mt-1 text-xs text-secondary">{service._count.complexityLevels > 0 ? `${service._count.complexityLevels} level tersedia` : "Tanpa complexity level"}</p></div>{service.isPublished ? <Eye className="size-5 shrink-0 text-success" aria-label="Dipublikasikan"/> : <EyeOff className="size-5 shrink-0 text-secondary" aria-label="Draf"/>}</div><p className="mt-5 line-clamp-2 text-sm leading-6 text-secondary">{service.summary}</p><div className="mt-6 flex flex-col justify-between gap-3 border-t border-border pt-5 sm:flex-row sm:items-center"><p className="text-xs text-secondary">Diperbarui {service.updatedAt.toLocaleDateString("id-ID")}</p>{archiveMode ? <form action={restoreArchivedServiceAction}><input type="hidden" name="serviceId" value={service.id}/><Button size="sm" variant="outline">Pulihkan</Button></form> : <Button asChild size="sm" variant="outline"><Link href={`/owner/services/${service.id}/edit`}><Pencil className="size-4" aria-hidden="true"/>Edit</Link></Button>}</div></div></WorkspaceModule>)}</div>}
    <PaginationControls pathname="/owner/services" page={page} hasNext={hasNext} params={{ q: q || undefined, type: selectedType?.slug, archive: archiveMode ? "1" : undefined }}/>
  </>;
}

function Metric({ label, value }: { label: string; value: number }) {
  return <div className="bg-surface p-5 md:p-6"><dt className="text-[10px] font-bold uppercase tracking-[.14em] text-muted">{label}</dt><dd className="mt-3 font-display text-4xl font-extrabold tabular-nums">{value}</dd></div>;
}

function CatalogRevertPreview({ preview }: { preview: CatalogRevertPreview }) {
  const archivable = preview.items.filter((item) => item.action === "ARCHIVE_CREATED");
  const restorable = preview.items.filter((item) => item.action === "RESTORE_UPDATED");
  const skipped = preview.items.filter((item) => !["ARCHIVE_CREATED", "RESTORE_UPDATED"].includes(item.action));
  return <section className="mt-6 rounded-[16px] border border-warning/30 bg-warning-soft/20 p-5 md:p-6" aria-labelledby="catalog-revert-title"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-primary">{preview.legacy ? "Legacy preview — konfirmasi ekstra" : "Preview revert import"}</p><h2 id="catalog-revert-title" className="mt-2 font-display text-2xl font-extrabold">Balikkan import {preview.source === "DEFAULT_CATALOG" ? "katalog default" : "Services III"}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-secondary">{preview.legacy ? "Record lama tidak memiliki snapshot. Aksi ini hanya mengarsipkan draft yang cocok dan aman; perubahan copy lama tidak dapat dipulihkan otomatis." : "Draft yang dibuat import akan diarsipkan. Draft existing yang diubah akan dipulihkan dari snapshot bila belum berubah setelah import."}</p></div><form action={revertCatalogImportAction} className="space-y-3"><input type="hidden" name="source" value={preview.source}/>{preview.runId ? <input type="hidden" name="runId" value={preview.runId}/> : <input type="hidden" name="legacy" value="true"/>}{preview.legacy ? <label className="flex max-w-xs items-start gap-2 text-xs leading-5 text-secondary"><input name="confirmed" type="checkbox" required className="mt-1 size-4 accent-primary"/>Saya memahami legacy revert hanya mengarsipkan draft cocok dan tidak dapat memulihkan copy sebelumnya.</label> : null}<Button type="submit" variant="outline">Konfirmasi revert aman</Button></form></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><RevertMetric label="Diarsipkan" value={archivable.length}/><RevertMetric label="Dipulihkan" value={restorable.length}/><RevertMetric label="Dilewati aman" value={skipped.length}/></div><div className="mt-6 grid gap-4 lg:grid-cols-2">{[{ label: "Aman dibalik", items: [...archivable, ...restorable] }, { label: "Dilewati", items: skipped }].filter((group) => group.items.length > 0).map((group) => <div key={group.label} className="rounded-[12px] border border-border bg-surface p-4"><h3 className="text-sm font-bold">{group.label} ({group.items.length})</h3><ul className="mt-3 space-y-2 text-sm text-secondary">{group.items.map((item) => <li key={`${item.action}-${item.serviceId}`}><span className="font-semibold text-foreground">{item.service}</span>{item.reason ? <span className="block text-xs">{item.reason}</span> : null}</li>)}</ul></div>)}</div></section>;
}

function RevertMetric({ label, value }: { label: string; value: number }) { return <div className="rounded-[12px] border border-border bg-surface p-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted">{label}</p><p className="mt-2 font-display text-3xl font-extrabold">{value}</p></div>; }

function ServicesThreePreview({ preview }: { preview: ServicesThreeImportPreview }) {
  const groups = [
    { key: "CREATE_DRAFT", label: "Draft baru", items: preview.items.filter((item) => item.action === "CREATE_DRAFT") },
    { key: "UPDATE_DRAFT", label: "Draft diperbarui", items: preview.items.filter((item) => item.action === "UPDATE_DRAFT") },
    { key: "SKIP_PROTECTED", label: "Published / historis dilindungi", items: preview.items.filter((item) => item.action === "SKIP_PROTECTED") },
    { key: "SKIP_MISSING_TYPE", label: "Jenis layanan tidak ditemukan", items: preview.items.filter((item) => item.action === "SKIP_MISSING_TYPE") },
  ].filter((group) => group.items.length > 0);

  return <section className="mt-6 rounded-[16px] border border-primary/25 bg-accent-soft/35 p-5 md:p-6" aria-labelledby="services-three-preview-title"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-primary">Preview tanpa perubahan data</p><h2 id="services-three-preview-title" className="mt-2 font-display text-2xl font-extrabold">Dampak preset Services III</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-secondary">Tinjau dampak import sebelum menerapkannya. Konfirmasi di bawah hanya membuat atau memperbarui draft; record published dan historis tetap dilindungi.</p></div><form action={importServicesThreeCatalogAction}><Button type="submit">Terapkan preset sebagai draft</Button></form></div><dl className="mt-6 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-3"><Metric label="Draft baru" value={preview.createdServices}/><Metric label="Draft diperbarui" value={preview.updatedDraftServices}/><Metric label="Record dilindungi" value={preview.skippedProtectedServices + preview.skippedMissingTypes}/></dl><p className="mt-4 text-xs leading-5 text-secondary">Level: {preview.createdLevels} baru · {preview.updatedDraftLevels} draft diperbarui · {preview.skippedPublishedLevels} published dilindungi.</p><div className="mt-6 grid gap-4 lg:grid-cols-2">{groups.map((group) => <div key={group.key} className="rounded-[12px] border border-border bg-surface p-4"><h3 className="text-sm font-bold">{group.label} <span className="text-secondary">({group.items.length})</span></h3><ul className="mt-3 space-y-2 text-sm text-secondary">{group.items.map((item) => <li key={`${group.key}-${item.service}`}><span className="font-semibold text-foreground">{item.service}</span><span className="block text-xs">{item.sourceCategory} · {item.levelsToCreate} level baru · {item.levelsToUpdate} level draft update{item.publishedLevelsProtected ? ` · ${item.publishedLevelsProtected} level published dilindungi` : ""}</span></li>)}</ul></div>)}</div></section>;
}
