import Link from "next/link";
import { Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";
export const dynamic="force-dynamic";
const variant=(status:string)=>status==="ACCEPTED"?"success":status==="REJECTED"||status==="CANCELLED"||status==="EXPIRED"?"error":status==="REVISION_REQUESTED"?"warning":"default" as const;
export default async function QuotationsPage(){const quotations=await prisma.quotation.findMany({where:{isCurrent:true},orderBy:{updatedAt:"desc"},take:100});return <><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Quotations</p><h1 className="mt-3 font-display text-3xl font-extrabold">Scope and price before commitment.</h1></div><Button asChild><Link href="/owner/quotations/create"><Plus className="size-4"/>Create Quotation</Link></Button></div><Card className="mt-8 overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-border bg-surface-container/50 text-xs uppercase tracking-wide text-secondary"><tr><th className="px-5 py-4">Quotation</th><th className="px-5 py-4">Client</th><th className="px-5 py-4">Project</th><th className="px-5 py-4">Total</th><th className="px-5 py-4">Valid until</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{quotations.map((quote)=><tr key={quote.id} className="border-b border-border last:border-0 hover:bg-accent-soft/40"><td className="px-5 py-4"><Link href={`/owner/quotations/${quote.id}`} className="font-semibold text-primary hover:underline">{quote.quotationNumber}</Link><p className="mt-1 text-xs text-secondary">Version {quote.version}</p></td><td className="px-5 py-4">{quote.clientName}</td><td className="px-5 py-4">{quote.projectTitle}</td><td className="px-5 py-4 font-semibold">{formatIdr(quote.total.toString())}</td><td className="px-5 py-4 text-secondary">{quote.validUntil.toLocaleDateString("id-ID")}</td><td className="px-5 py-4"><Badge variant={variant(quote.status)}>{quote.status.replaceAll("_"," ")}</Badge></td></tr>)}</tbody></table>{quotations.length===0&&<p className="p-10 text-center text-sm text-secondary">No quotations yet.</p>}</div></CardContent></Card></>}
