import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { submitContactAction } from "@/features/contact/actions";
export default async function ContactPage({searchParams}:{searchParams:Promise<{sent?:string}>}){const {sent}=await searchParams;return <><SiteHeader/><main className="mx-auto grid max-w-[1100px] gap-12 px-5 py-20 md:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Contact</p><h1 className="text-balance mt-4 font-display text-5xl font-extrabold tracking-[-0.05em]">Let’s understand the project first.</h1><p className="mt-6 leading-7 text-secondary">Use this form for general questions. For a structured project request, start with the project brief so the discussion can continue with an inquiry reference.</p></div><Card><CardContent className="p-7 md:p-9">{sent&&<p className="mb-6 rounded-[10px] bg-accent-soft p-4 text-sm font-semibold text-primary">Message received. RRS will respond through the contact details provided.</p>}<form action={submitContactAction} className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name"/><Field label="Email" name="email" type="email"/><Field label="WhatsApp (optional)" name="whatsappNumber" required={false}/><Field label="Subject" name="subject"/><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Message</span><Textarea name="message" required/></label><Button className="sm:col-span-2">Send Message</Button></form></CardContent></Card></main><SiteFooter/></>}
function Field({label,name,type="text",required=true}:{label:string;name:string;type?:string;required?:boolean}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><Input name={name} type={type} required={required}/></label>}
