import { MessageCircle } from "lucide-react";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { ContactForm } from "@/features/contact/contact-form";
import { getServerEnv } from "@/lib/env";
import { createWhatsAppUrl, formatWhatsAppNumber } from "@/lib/whatsapp";

export default async function ContactPage({searchParams}:{searchParams:Promise<{sent?:string}>}){const [{sent},env]=await Promise.all([searchParams,Promise.resolve(getServerEnv())]);const whatsappNumber=formatWhatsAppNumber(env.OWNER_WHATSAPP_NUMBER);const whatsapp=createWhatsAppUrl(env.OWNER_WHATSAPP_NUMBER,"Halo Radhiansyah Putra, saya ingin berdiskusi mengenai kebutuhan project digital.");return <><SiteHeader/><main className="mx-auto grid max-w-[1100px] gap-12 px-5 py-20 md:px-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Kontak</p><h1 className="text-balance mt-4 font-display text-5xl font-extrabold tracking-[-0.05em]">Mari pahami kebutuhan project terlebih dahulu.</h1><p className="mt-6 leading-7 text-secondary">Gunakan form untuk pertanyaan umum, atau hubungi langsung melalui WhatsApp. Untuk permintaan project yang terstruktur, mulai dari brief agar diskusi memiliki referensi inquiry.</p><Card className="mt-8 border-primary/20 bg-accent-soft"><CardContent><MessageCircle className="size-5 text-primary"/><p className="mt-4 text-sm font-semibold">Diskusi langsung melalui WhatsApp</p><p className="mt-2 text-sm text-secondary">{whatsappNumber}</p><Button asChild className="mt-5" size="sm"><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle className="size-4"/>Chat WhatsApp</a></Button></CardContent></Card></div><Card><CardContent className="p-7 md:p-9">{sent&&<p className="mb-6 rounded-[10px] bg-accent-soft p-4 text-sm font-semibold text-primary">Pesan diterima. RRS akan membalas melalui kontak yang Anda cantumkan.</p>}<ContactForm/></CardContent></Card></main><SiteFooter/></>}
