import { ReviewStatus } from "@/generated/prisma/enums";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { moderateReviewAction } from "@/features/reviews/actions";
import { prisma } from "@/lib/db/prisma";
export const dynamic="force-dynamic";const selectClass="h-11 rounded-[10px] border border-border bg-surface px-3 text-sm";
export default async function OwnerReviewsPage(){const reviews=await prisma.review.findMany({include:{client:true,project:true},orderBy:{submittedAt:"desc"}});return <><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Reviews</p><h1 className="mt-3 font-display text-3xl font-extrabold">Moderate feedback from completed projects.</h1><div className="mt-8 space-y-5">{reviews.map((review)=><Card key={review.id}><CardContent><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="font-display text-lg font-extrabold">{review.client.name}</p><p className="mt-1 text-xs text-secondary">{review.project.projectNumber} · {review.project.title}</p></div><Badge>{review.status}</Badge></div><p className="mt-5 leading-7 text-secondary">“{review.comment}”</p><p className="mt-3 text-sm font-semibold text-primary">Overall {review.overallRating}/5 · Communication {review.communicationRating}/5 · Quality {review.qualityRating}/5</p><form action={moderateReviewAction} className="mt-6 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="reviewId" value={review.id}/><select name="status" defaultValue={review.status} className={selectClass}>{Object.values(ReviewStatus).map((status)=><option key={status}>{status}</option>)}</select><Textarea name="ownerResponse" defaultValue={review.ownerResponse??""} placeholder="Optional public owner response" className="min-h-20"/><Button>Save Moderation</Button></form></CardContent></Card>)}</div>{reviews.length===0&&<p className="mt-8 rounded-[14px] border border-dashed border-border p-10 text-center text-sm text-secondary">No verified review submissions yet.</p>}</>}
