"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { ReviewStatus } from "@/generated/prisma/enums";
import { prisma } from "@/lib/db/prisma";
import { hashPublicToken } from "@/lib/security/tokens";
import { requireOwner } from "@/lib/authz";
const reviewSchema=z.object({token:z.string().min(20),overallRating:z.coerce.number().int().min(1).max(5),communicationRating:z.coerce.number().int().min(1).max(5),qualityRating:z.coerce.number().int().min(1).max(5),deliveryRating:z.coerce.number().int().min(1).max(5),valueRating:z.coerce.number().int().min(1).max(5),comment:z.string().trim().min(20).max(5000)});
export async function submitReviewAction(formData:FormData){const data=reviewSchema.parse(Object.fromEntries(formData));const hash=hashPublicToken(data.token);await prisma.$transaction(async(tx)=>{const invitation=await tx.reviewInvitation.findUnique({where:{tokenHash:hash},include:{project:{include:{quotation:true}},review:true}});if(!invitation||invitation.revokedAt||invitation.usedAt||invitation.expiresAt<new Date()||invitation.project.status!=="COMPLETED"||invitation.review)throw new Error("Review invitation is invalid or already used.");await tx.review.create({data:{projectId:invitation.projectId,invitationId:invitation.id,clientId:invitation.project.clientId,serviceId:invitation.project.quotation.serviceId,overallRating:data.overallRating,communicationRating:data.communicationRating,qualityRating:data.qualityRating,deliveryRating:data.deliveryRating,valueRating:data.valueRating,comment:data.comment,status:"PENDING",isPublished:false}});await tx.reviewInvitation.update({where:{id:invitation.id},data:{usedAt:new Date()}});await tx.projectActivity.create({data:{projectId:invitation.projectId,type:"REVIEW_SUBMITTED",description:"Client submitted a verified project review for moderation."}});});redirect(`/review/${data.token}?submitted=1`)}
export async function moderateReviewAction(formData:FormData){await requireOwner();const data=z.object({reviewId:z.string(),status:z.enum(ReviewStatus),ownerResponse:z.string().trim().max(5000).optional()}).parse(Object.fromEntries(formData));const publish=data.status==="PUBLISHED";await prisma.review.update({where:{id:data.reviewId},data:{status:data.status,isPublished:publish,publishedAt:publish?new Date():null,ownerResponse:data.ownerResponse||null}});revalidatePath("/owner/reviews");revalidatePath("/reviews")}
