import Link from "next/link";
import { ArrowRight, Check, FileCheck2, Search, ShieldCheck } from "lucide-react";
import { SiteFooter } from "@/components/layout/site-footer";
import { PageEntrance } from "@/components/page-entrance";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getDictionary } from "@/i18n/dictionaries";
import { getLocale } from "@/i18n/server";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function Home() {
  const locale = await getLocale(); const dictionary = getDictionary(locale); const isId = locale === "id";
  const services = await prisma.service.findMany({ where: { isPublished: true }, orderBy: [{ isFeatured: "desc" }, { updatedAt: "desc" }], take: 3 });
  const benefits = isId ? [
    ["01", "Scope sebelum development", "Requirement, batas pekerjaan, dan prioritas disepakati sebelum coding dimulai."],
    ["02", "Quotation yang dapat ditinjau", "Harga, timeline, payment term, revisi, dan pengecualian ditulis secara formal."],
    ["03", "Satu portal untuk progress", "Milestone, file, approval, invoice, dan pembaruan project berada dalam satu tempat."],
    ["04", "Delivery yang terdokumentasi", "Hasil akhir, revisi, dan persetujuan client tersimpan dengan jelas."],
  ] : [
    ["01", "Scope before development", "Requirements, boundaries, and priorities are agreed before implementation begins."],
    ["02", "A quotation you can review", "Price, timeline, payment terms, revisions, and exclusions are documented formally."],
    ["03", "One portal for progress", "Milestones, files, approvals, invoices, and project updates stay in one place."],
    ["04", "Documented delivery", "Final work, revisions, and client approval remain clear and traceable."],
  ];
  const steps = isId ? [["01","Kirim brief","Ceritakan tujuan, kebutuhan, budget, dan timeline awal."],["02","Diskusi di WhatsApp","Kita menyaring asumsi dan menentukan prioritas yang realistis."],["03","Tinjau quotation","Scope, harga, timeline, revisi, dan pembayaran ditulis sebelum project dimulai."],["04","Pantau project","Progress, file, approval, dan invoice dikelola melalui portal client."],["05","Setujui hasil","Delivery ditinjau, disetujui, lalu ditutup dengan review terverifikasi."]] : [["01","Share the brief","Describe the goal, requirements, budget, and initial timeline."],["02","Discuss on WhatsApp","We remove assumptions and establish realistic priorities."],["03","Review the quotation","Scope, price, timeline, revisions, and payments are documented before work begins."],["04","Track the project","Progress, files, approvals, and invoices are managed in the client portal."],["05","Approve delivery","Review the final work, approve delivery, and close with a verified review."]];
  return <><SiteHeader/><PageEntrance><main>
    <section className="border-b border-border"><div className="mx-auto grid max-w-[1360px] gap-14 px-5 py-20 md:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-28 xl:px-16">
      <div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{isId?"Independent Web & Product Studio":"Independent Web & Product Studio"}</p><h1 className="text-balance mt-6 max-w-3xl font-display text-[clamp(3rem,6.8vw,6.25rem)] font-extrabold leading-[.95] tracking-[-0.065em]">{isId?"Bangun project digital dengan scope yang jelas.":"Build digital products with a clear scope."}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-secondary">{isId?"Saya membantu merancang dan membangun website serta aplikasi melalui proses brief, konsultasi, quotation, dan delivery yang transparan.":"I design and build websites and applications through a transparent brief, consultation, quotation, and delivery process."}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/start-project">{isId?"Kirim Brief Project":"Share Your Project Brief"}<ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline"><Link href="/cara-kerja">{dictionary.nav.process}</Link></Button></div><p className="mt-6 flex items-center gap-2 text-sm font-medium text-secondary"><ShieldCheck className="size-4 text-primary"/>{isId?"Tanpa checkout instan. Harga final hanya melalui quotation.":"No instant checkout. Final pricing is documented in a quotation."}</p>
      </div>
      <div className="relative flex items-center justify-center lg:justify-end" aria-label={isId?"Contoh quotation dan progress project":"Sample quotation and project progress"}><div className="absolute inset-y-8 right-0 hidden w-[82%] bg-primary lg:block"/><article className="relative w-full max-w-[680px] border border-border bg-surface p-6 shadow-[0_24px_70px_rgba(17,17,17,.10)] md:p-9" data-motion-card><div className="flex items-start justify-between gap-6 border-b border-border pb-7"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-secondary">{isId?"Contoh quotation · Data demonstrasi":"Sample quotation · Demonstration data"}</p><h2 className="mt-3 font-display text-2xl font-extrabold">QT-2026-0012 <span className="text-secondary">/ v2</span></h2></div><span className="rounded-[6px] bg-[#fff4d1] px-2.5 py-1 text-xs font-bold text-[#805b00]">{isId?"Ditinjau":"In review"}</span></div><div className="grid gap-6 border-b border-border py-7 sm:grid-cols-2"><QuoteMeta label={isId?"Disiapkan untuk":"Prepared for"} value={isId?"Contoh Perusahaan Digital":"Sample Digital Company"}/><QuoteMeta label="Project" value="Company Profile Redesign"/><QuoteMeta label={isId?"Berlaku hingga":"Valid until"} value="30 Juli 2026"/><QuoteMeta label="Timeline" value={isId?"5–7 minggu":"5 - 20 Hari"}/></div><div className="space-y-4 py-7 text-sm"><QuoteLine label="Product discovery & UI/UX" value="Rp 400.000"/><QuoteLine label="Development & CMS" value="Rp 700.000"/><QuoteLine label="SEO & deployment foundation" value="Rp 250.000"/></div><div className="flex items-end justify-between border-t border-border pt-6"><div><p className="text-xs text-secondary">{isId?"Revisi":"Revisions"}</p><p className="mt-1 font-semibold">2 {isId?"putaran":"rounds"}</p></div><div className="text-right"><p className="text-xs text-secondary">{isId?"Estimasi total":"Estimated total"}</p><p className="mt-1 font-display text-2xl font-extrabold text-primary">Rp 1.350.000</p></div></div></article><div className="absolute -bottom-6 left-4 hidden w-64 border border-border bg-[#0c4032] p-5 text-white shadow-lg sm:block" data-motion-card><div className="flex items-center justify-between text-xs text-white/65"><span>{isId?"Project aktif":"Active project"}</span><span>65%</span></div><div className="mt-4 h-1.5 bg-white/15"><div className="h-full w-[65%] bg-[#9ad6b8]"/></div><p className="mt-3 text-sm font-semibold">{isId?"Development berlangsung":"Development in progress"}</p></div></div>
    </div></section>

    <section data-reveal className="mx-auto max-w-[1360px] px-5 py-24 md:px-8 lg:px-12 lg:py-32 xl:px-16"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{isId?"Bekerja dengan lebih jelas":"A clearer way to work"}</p><h2 className="text-balance mt-5 font-display text-4xl font-extrabold tracking-[-.045em] md:text-5xl">{isId?"Kejelasan bukan tambahan. Itu fondasi project.":"Clarity is not an extra. It is the project foundation."}</h2></div><ol data-reveal-group className="border-t border-border">{benefits.map(([number,title,description])=><li key={number} data-reveal-item className="grid gap-3 border-b border-border py-7 sm:grid-cols-[64px_1fr_1.1fr]"><span className="text-xs font-bold text-primary">{number}</span><h3 className="font-display text-xl font-extrabold">{title}</h3><p className="text-sm leading-7 text-secondary">{description}</p></li>)}</ol></div></section>

    <section data-reveal className="border-y border-border bg-surface"><div className="mx-auto max-w-[1360px] px-5 py-24 md:px-8 lg:px-12 lg:py-32 xl:px-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{isId?"Layanan terpilih":"Selected services"}</p><h2 className="mt-5 max-w-3xl font-display text-4xl font-extrabold tracking-[-.045em] md:text-5xl">{isId?"Keahlian yang disusun mengikuti project.":"Expertise shaped around the project."}</h2></div><Button asChild variant="outline"><Link href="/services">{dictionary.home.secondary}<ArrowRight className="size-4"/></Link></Button></div>{services.length>0?<div data-reveal-group className="mt-14 grid gap-px bg-border lg:grid-cols-2">{services.map((service,index)=><article key={service.id} data-reveal-item data-motion-card className={index===0?"group bg-background p-7 lg:row-span-2 lg:p-10":"group bg-background p-7 lg:p-8"}><div data-card-media className={index===0?"min-h-64 border border-border bg-[#0c4032] p-7 text-white":"min-h-36 border border-border bg-surface-container p-6"}><ServiceVisual index={index} title={service.title}/></div><p className="mt-7 text-xs font-bold uppercase tracking-[.14em] text-primary">{service.category}</p><h3 className={index===0?"mt-3 font-display text-3xl font-extrabold":"mt-3 font-display text-2xl font-extrabold"}>{service.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-secondary">{service.summary}</p><div className="mt-8 flex flex-wrap items-end justify-between gap-5 border-t border-border pt-5"><div><p className="text-xs text-secondary">{isId?"Estimasi awal":"Starting estimate"}</p><p className="mt-1 font-display text-xl font-extrabold">{service.startingPrice?`${formatIdr(service.startingPrice.toString())}+`:(isId?"Sesuai scope":"Custom scope")}</p></div><Link href={`/services/${service.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-primary">{isId?"Lihat detail":"View details"}<ArrowRight className="size-4"/></Link></div></article>)}</div>:<p className="mt-12 border-t border-border py-10 text-secondary">{isId?"Layanan publik sedang disiapkan.":"Published services are being prepared."}</p>}<p className="mt-6 text-xs text-secondary">{isId?"Harga final ditentukan berdasarkan scope quotation.":"Final pricing is determined by the documented quotation scope."}</p></div></section>

    <section id="process" data-reveal className="mx-auto max-w-[1360px] px-5 py-24 md:px-8 lg:px-12 lg:py-32 xl:px-16"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{dictionary.home.processEyebrow}</p><h2 className="mt-5 font-display text-4xl font-extrabold tracking-[-.045em] md:text-5xl">{isId?"Dari konteks awal hingga delivery.":"From initial context to delivery."}</h2><p className="mt-5 max-w-md text-sm leading-7 text-secondary">{dictionary.home.processDescription}</p><Button asChild variant="outline" className="mt-7"><Link href="/cara-kerja">{isId?"Pelajari alurnya":"Explore the workflow"}<ArrowRight className="size-4"/></Link></Button></div><ol data-reveal-group className="border-t border-border">{steps.map(([n,title,description])=><li key={n} data-reveal-item className="grid gap-3 border-b border-border py-6 sm:grid-cols-[56px_180px_1fr]"><span className="text-xs font-bold text-primary">{n}</span><h3 className="font-display text-lg font-extrabold">{title}</h3><p className="text-sm leading-7 text-secondary">{description}</p></li>)}</ol></div></section>

    <section data-reveal className="bg-[#092f26] text-white"><div className="mx-auto grid max-w-[1360px] gap-14 px-5 py-24 md:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-32 xl:px-16"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#9ad6b8]">{isId?"Quotation sebagai fondasi":"Quotation as the foundation"}</p><h2 className="mt-5 font-display text-4xl font-extrabold tracking-[-.045em] md:text-5xl">{isId?"Ketahui apa yang dibangun sebelum pekerjaan dimulai.":"Know what will be built before the work begins."}</h2><p className="mt-6 max-w-lg text-base leading-8 text-white/65">{dictionary.home.quoteDescription}</p><p className="mt-7 flex items-start gap-3 text-sm text-white/80"><FileCheck2 className="mt-0.5 size-5 shrink-0 text-[#9ad6b8]"/>{dictionary.home.noPayment}</p></div><div className="grid gap-px bg-white/15 sm:grid-cols-2">{[isId?"Scope termasuk dan tidak termasuk":"Included and excluded scope",isId?"Timeline dan batas revisi":"Timeline and revision limit",isId?"Jadwal pembayaran":"Payment schedule",isId?"Versioning dan persetujuan client":"Versioning and client approval"].map(item=><div key={item} className="flex items-start gap-3 bg-[#0c4032] p-6"><Check className="mt-0.5 size-4 shrink-0 text-[#9ad6b8]"/><p className="text-sm font-semibold leading-6">{item}</p></div>)}</div></div></section>

    <section data-reveal className="mx-auto max-w-[1360px] px-5 py-24 md:px-8 lg:px-12 lg:py-32 xl:px-16"><div className="grid gap-10 border-y border-border py-14 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{isId?"Mulai dari konteks":"Start with context"}</p><h2 className="mt-5 max-w-4xl font-display text-4xl font-extrabold tracking-[-.045em] md:text-6xl">{isId?"Punya project yang masih belum jelas scope-nya?":"Still working out the scope of your project?"}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-secondary">{isId?"Kirim brief awal. Kita bahas kebutuhan, prioritas, dan estimasi sebelum quotation dibuat.":"Share an initial brief. We will discuss requirements, priorities, and estimates before preparing a quotation."}</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Button asChild size="lg"><Link href="/start-project">{isId?"Kirim Brief Project":"Share Project Brief"}<ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline"><Link href="/cara-kerja">{dictionary.nav.process}</Link></Button></div></div><form action="/services" className="relative mt-10 max-w-2xl"><Search className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-secondary"/><Input name="q" aria-label="Search services" placeholder={dictionary.home.searchPlaceholder} className="h-14 pl-12 pr-28"/><Button type="submit" size="sm" className="absolute right-2 top-2 h-10">{dictionary.common.search}</Button></form></section>
  </main></PageEntrance><SiteFooter/></>;
}

function QuoteMeta({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-secondary">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
function QuoteLine({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-5"><span className="text-secondary">{label}</span><span className="font-semibold">{value}</span></div>}
function ServiceVisual({index,title}:{index:number;title:string}){if(index===0)return <><p className="text-xs font-semibold text-white/60">RRS / Product workspace</p><div className="mt-8 grid grid-cols-[.8fr_1.2fr] gap-3"><div className="space-y-3"><div className="h-2 w-16 bg-white/30"/><div className="h-2 w-24 bg-white/15"/><div className="h-20 border border-white/20"/></div><div className="border border-white/20 p-4"><div className="h-2 w-20 bg-[#9ad6b8]"/><div className="mt-5 grid grid-cols-3 gap-2">{[1,2,3].map(i=><div key={i} className="h-12 bg-white/10"/>)}</div></div></div><p className="mt-6 font-display text-xl font-extrabold">{title}</p></>;return <><p className="text-xs font-semibold text-secondary">RRS / {index===1?"Interface system":"Business website"}</p><div className="mt-6 grid grid-cols-4 gap-2">{[1,2,3,4].map(i=><div key={i} className={`h-14 border border-border ${i===1?"bg-primary":"bg-surface"}`}/>)}</div></>}
