import Link from "next/link";
import { notFound } from "next/navigation";
import { InvoiceDocument } from "@/components/invoice-document";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { MidtransPaymentControl, ManualPaymentControl } from "@/features/payments/client-payment-controls";
import { requireClient } from "@/lib/authz";
import { getServerEnv } from "@/lib/env";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";
export const dynamic="force-dynamic";
export default async function ClientInvoiceDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{payment?:string}>}){const user=await requireClient();const {id}=await params;const {payment:paymentId}=await searchParams;const invoice=await prisma.invoice.findFirst({where:{id,clientId:user.id},include:{client:true,project:true,paymentSchedule:true,payments:{include:{files:true},orderBy:{createdAt:"desc"}}}});if(!invoice)notFound();const selected=paymentId?invoice.payments.find((item)=>item.id===paymentId):invoice.payments[0];const payable=!["PAID","VOID","REFUNDED"].includes(invoice.status)&&Number(invoice.paidAmount)<Number(invoice.total);const midtransConfigured=Boolean(getServerEnv().MIDTRANS_SERVER_KEY);return <><InvoiceDocument invoice={invoice}/>{selected&&<Card className="mt-5"><CardContent><div className="flex justify-between gap-4"><div><p className="font-semibold">Latest payment attempt</p><p className="mt-1 text-xs text-secondary">{selected.provider} · {selected.createdAt.toLocaleString("id-ID")}</p></div><Badge>{selected.manualStatus??selected.status}</Badge></div>{selected.checkoutUrl&&selected.status==="PROCESSING"&&<Button asChild className="mt-5"><a href={selected.checkoutUrl} target="_blank" rel="noreferrer">Continue Midtrans Payment</a></Button>}{selected.rejectionReason&&<p className="mt-4 rounded-[10px] bg-[#fbe8e8] p-3 text-sm text-error">{selected.rejectionReason}</p>}</CardContent></Card>}{payable&&<div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardContent><h2 className="font-display text-lg font-extrabold">Pay with Midtrans Sandbox</h2><p className="mt-2 text-sm leading-6 text-secondary">A Snap transaction is created for the current outstanding invoice amount: {formatIdr(Number(invoice.total)-Number(invoice.paidAmount))}.</p><MidtransPaymentControl invoiceId={invoice.id} enabled={midtransConfigured}/></CardContent></Card><Card><CardContent><h2 className="font-display text-lg font-extrabold">Submit manual payment proof</h2><p className="mt-2 text-sm leading-6 text-secondary">Upload a private JPG, PNG, WebP, or PDF. The owner must verify it before the invoice changes to paid.</p><ManualPaymentControl invoiceId={invoice.id}/></CardContent></Card></div>}<p className="mt-6 text-sm"><Link href="/client/invoices" className="font-semibold text-primary hover:underline">Back to invoices</Link></p></>}
