"use client";

import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { FieldError, fieldErrorClass } from "@/components/ui/field-error";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { acceptQuotationAction, rejectQuotationAction, requestQuotationRevisionAction, type PublicQuotationActionState } from "@/features/quotations/public-actions";

const empty: PublicQuotationActionState = {};
export function PublicQuotationDecisionPanel({ token, name, email, phone, isId }: { token: string; name: string; email: string; phone: string; isId: boolean }) {
  return <section className="mt-12 print:hidden"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{isId ? "Keputusan client" : "Client decision"}</p><h2 className="mt-4 font-display text-3xl font-extrabold">{isId ? "Tinjau versi ini dengan jelas." : "Review this version clearly."}</h2><p className="mt-3 text-sm text-secondary">{isId ? "Terima quotation, minta perubahan spesifik, atau jelaskan alasan penolakan." : "Accept the quotation, request specific changes, or explain why it is not suitable."}</p><div className="mt-8 grid gap-px bg-border lg:grid-cols-3"><Accept token={token} name={name} email={email} phone={phone} isId={isId}/><Revision token={token} name={name} isId={isId}/><Reject token={token} isId={isId}/></div></section>;
}
function InlineFieldError({ error }: { error?: string }) { return <FieldError id="quote-field-error" error={error}/>; }
function Notice({ message }: { message?: string }) { return message ? <p role="alert" className="mt-3 rounded-[10px] bg-[#fbe8e8] px-3 py-3 text-xs leading-5 text-error">{message}</p> : null; }
function Box({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <article className="bg-surface p-6"><h3 className="font-display text-xl font-extrabold">{title}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-secondary">{description}</p><div className="mt-6">{children}</div></article>; }
function Accept({ token, name, email, phone, isId }: { token: string; name: string; email: string; phone: string; isId: boolean }) { const [state, action, pending] = useActionState(acceptQuotationAction, empty); const error=(key:string)=>state.errors?.[key]?.[0]; return <Box title={isId?"Terima quotation":"Accept quotation"} description={isId?"Konfirmasi identitas dan persetujuan terhadap terms yang didokumentasikan.":"Confirm your identity and agreement with the documented terms."}><form action={action} className="space-y-3"><input type="hidden" name="token" value={token}/><Input name="name" placeholder={isId?"Nama lengkap":"Full name"} defaultValue={name} required className={fieldErrorClass(error("name"))}/><InlineFieldError error={error("name")}/><Input name="email" type="email" placeholder="Email" defaultValue={email} required className={fieldErrorClass(error("email"))}/><InlineFieldError error={error("email")}/><Input name="phone" placeholder={isId?"Nomor WhatsApp":"WhatsApp number"} defaultValue={phone} required className={fieldErrorClass(error("phone"))}/><InlineFieldError error={error("phone")}/><label className="flex items-start gap-2 text-xs text-secondary"><input name="acceptTerms" type="checkbox" required className="mt-0.5"/>{isId?"Saya telah membaca dan menyetujui quotation beserta syaratnya.":"I have read and agree to this quotation and its terms."}</label><InlineFieldError error={error("acceptTerms")}/><Notice message={state.message}/><Button className="w-full" disabled={pending}>{pending?(isId?"Memproses…":"Processing…"):(isId?"Terima Quotation":"Accept Quotation")}</Button></form></Box>; }
function Revision({ token, name, isId }: { token:string; name:string; isId:boolean }) { const [state, action, pending] = useActionState(requestQuotationRevisionAction, empty); const error=(key:string)=>state.errors?.[key]?.[0]; return <Box title={isId?"Minta revisi":"Request revision"} description={isId?"Jelaskan perubahan pada scope, harga, timeline, atau terms.":"Describe changes to scope, price, timeline, or terms."}><form action={action} className="space-y-3"><input type="hidden" name="token" value={token}/><Input name="requestedBy" placeholder={isId?"Nama Anda":"Your name"} defaultValue={name} required className={fieldErrorClass(error("requestedBy"))}/><InlineFieldError error={error("requestedBy")}/><Textarea name="reason" placeholder={isId?"Jelaskan perubahan yang diminta":"Describe the requested changes"} required className={fieldErrorClass(error("reason"))}/><InlineFieldError error={error("reason")}/><Notice message={state.message}/><Button variant="outline" className="w-full" disabled={pending}>{isId?"Minta Revisi":"Request Revision"}</Button></form></Box>; }
function Reject({ token, isId }: { token:string; isId:boolean }) { const [state, action, pending] = useActionState(rejectQuotationAction, empty); const error=state.errors?.reason?.[0]; return <Box title={isId?"Tolak quotation":"Reject quotation"} description={isId?"Berikan alasan singkat agar keputusan dapat dipahami.":"Share a concise reason so the decision can be understood."}><form action={action} className="space-y-3"><input type="hidden" name="token" value={token}/><Textarea name="reason" placeholder={isId?"Alasan penolakan":"Reason for rejection"} required className={fieldErrorClass(error)}/><InlineFieldError error={error}/><Notice message={state.message}/><Button variant="ghost" className="w-full" disabled={pending}>{isId?"Tolak Quotation":"Reject Quotation"}</Button></form></Box>; }
