"use client";

import Link from "next/link";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { FieldError, fieldErrorClass } from "@/components/ui/field-error";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { acceptQuotationAction, createQuotationDiscussionAction, rejectQuotationAction, requestQuotationRevisionAction, type PublicQuotationActionState } from "@/features/quotations/public-actions";

const empty: PublicQuotationActionState = {};
type Session = { email?: string | null; role?: "OWNER" | "CLIENT" } | null;
export function PublicQuotationDecisionPanel({ token, recipientEmail, isId, session }: { token: string; recipientEmail?: string | null; isId: boolean; session: Session }) {
  const callbackUrl = `/quotation/${token}`;
  const matchingClient = session?.role === "CLIENT" && Boolean(session.email && recipientEmail && session.email.toLowerCase() === recipientEmail.toLowerCase());
  return <section className="mt-12 print:hidden"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{isId ? "Quotation" : "Quotation"}</p><h2 className="mt-4 font-display text-3xl font-extrabold">{isId ? "Lanjutkan dengan jalur yang sesuai." : "Continue with the right path."}</h2><p className="mt-3 text-sm text-secondary">{isId ? "Diskusi awal tetap terbuka. Keputusan formal quotation memerlukan login dengan email penerima quotation." : "Guest discussion remains available. Formal quotation decisions require the Client account that received this quotation."}</p><div className="mt-8 grid gap-px bg-border lg:grid-cols-2"><Discussion token={token} isId={isId}/>{matchingClient ? <Formal token={token} isId={isId}/> : <LoginGate callbackUrl={callbackUrl} isId={isId} wrongAccount={Boolean(session)}/>}</div></section>;
}
function Notice({ message }: { message?: string }) { return message ? <p role="alert" className="mt-3 rounded-[10px] bg-[#fbe8e8] px-3 py-3 text-xs leading-5 text-error">{message}</p> : null; }
function Box({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <article className="bg-surface p-6"><h3 className="font-display text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-secondary">{description}</p><div className="mt-6">{children}</div></article>; }
function Discussion({ token, isId }: { token: string; isId: boolean }) { const [state, action, pending] = useActionState(createQuotationDiscussionAction, empty); const error = (key: string) => state.errors?.[key]?.[0]; return <Box title={isId ? "Diskusikan quotation" : "Discuss this quotation"} description={isId ? "Tidak perlu login. Gunakan email yang menerima quotation agar pesan dapat diproses." : "No login required. Use the email that received this quotation so the message can be processed."}><form action={action} className="space-y-3"><input type="hidden" name="token" value={token}/><input type="text" name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><Input name="name" placeholder={isId ? "Nama" : "Name"} required className={fieldErrorClass(error("name"))}/><FieldError id="discussion-name-error" error={error("name")}/><Input name="email" type="email" placeholder="Email" required className={fieldErrorClass(error("email"))}/><FieldError id="discussion-email-error" error={error("email")}/><Textarea name="message" placeholder={isId ? "Tulis pertanyaan atau konteks yang ingin didiskusikan" : "Write your question or discussion context"} required className={fieldErrorClass(error("message"))}/><FieldError id="discussion-message-error" error={error("message")}/><Notice message={state.message}/><Button variant="outline" className="w-full" disabled={pending}>{pending ? (isId ? "Mengirim…" : "Sending…") : (isId ? "Kirim pertanyaan" : "Send question")}</Button></form></Box>; }
function LoginGate({ callbackUrl, isId, wrongAccount }: { callbackUrl: string; isId: boolean; wrongAccount: boolean }) { return <Box title={isId ? "Login untuk keputusan formal" : "Sign in for formal decisions"} description={wrongAccount ? (isId ? "Gunakan akun Client dengan email penerima quotation ini." : "Use the Client account with the quotation recipient email.") : (isId ? "Terima, revisi, atau tolak quotation dari akun Client yang menerima quotation." : "Accept, request a revision, or reject from the Client account that received this quotation.")}><Button asChild className="w-full"><Link href={`/login?callbackUrl=${encodeURIComponent(callbackUrl)}`}>{isId ? "Login untuk melanjutkan" : "Sign in to continue"}</Link></Button></Box>; }
function Formal({ token, isId }: { token: string; isId: boolean }) { const [acceptState, acceptAction, accepting] = useActionState(acceptQuotationAction, empty); const [revisionState, revisionAction, revising] = useActionState(requestQuotationRevisionAction, empty); const [rejectState, rejectAction, rejecting] = useActionState(rejectQuotationAction, empty); return <Box title={isId ? "Keputusan quotation" : "Quotation decision"} description={isId ? "Anda login dengan email recipient quotation. Pilih keputusan formal yang sesuai." : "You are signed in with the quotation recipient email. Choose the appropriate formal decision."}><form action={acceptAction} className="space-y-3"><input type="hidden" name="token" value={token}/><label className="flex items-start gap-2 text-xs text-secondary"><input name="acceptTerms" type="checkbox" required className="mt-0.5"/>{isId ? "Saya telah membaca dan menyetujui quotation beserta syaratnya." : "I have read and agree to this quotation and its terms."}</label><FieldError id="accept-terms-error" error={acceptState.errors?.acceptTerms?.[0]}/><Notice message={acceptState.message}/><Button className="w-full" disabled={accepting}>{isId ? "Terima quotation" : "Accept quotation"}</Button></form><details className="mt-4 border-t border-border pt-4"><summary className="cursor-pointer text-sm font-semibold">{isId ? "Minta revisi atau tolak" : "Request a revision or reject"}</summary><form action={revisionAction} className="mt-3 space-y-3"><input type="hidden" name="token" value={token}/><Textarea name="reason" placeholder={isId ? "Perubahan formal yang diminta" : "Requested formal changes"} required className={fieldErrorClass(revisionState.errors?.reason?.[0])}/><Notice message={revisionState.message}/><Button variant="outline" className="w-full" disabled={revising}>{isId ? "Minta revisi" : "Request revision"}</Button></form><form action={rejectAction} className="mt-3 space-y-3"><input type="hidden" name="token" value={token}/><Textarea name="reason" placeholder={isId ? "Alasan penolakan" : "Reason for rejection"} required className={fieldErrorClass(rejectState.errors?.reason?.[0])}/><Notice message={rejectState.message}/><Button variant="ghost" className="w-full" disabled={rejecting}>{isId ? "Tolak quotation" : "Reject quotation"}</Button></form></details></Box>; }
