"use client";

import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { saveQuotationAction } from "@/features/quotations/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { formatIdr } from "@/lib/utils";

type Item = { id: string; title: string; description: string; quantity: number; unitPrice: number };
export type QuotationDefaults = {
  quotationId?: string; inquiryId?: string; clientId?: string; quotationNumber?: string; version?: number;
  clientName?: string; companyName?: string; clientEmail?: string; clientPhone?: string; clientAddress?: string;
  projectTitle?: string; projectSummary?: string; projectType?: string; validUntil: string; estimatedStartDate?: string; estimatedCompletionAt?: string;
  discount?: number; tax?: number; paymentPlanType?: string; customFirstPayment?: number; scopeIncluded?: string; scopeExcluded?: string; revisionLimit?: number; maintenanceDays?: number; terms?: string; notes?: string; items?: Omit<Item,"id">[];
};
const selectClass="h-12 w-full rounded-[12px] border border-border bg-surface px-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10";

export function QuotationBuilder({ defaults }: { defaults: QuotationDefaults }) {
  const [state, action, pending] = useActionState(saveQuotationAction, {});
  const dirtyRef = useRef(false);
  const [items, setItems] = useState<Item[]>((defaults.items?.length ? defaults.items : [{ title: "", description: "", quantity: 1, unitPrice: 0 }]).map((item,index)=>({ ...item, id: `item-${index}` })));
  const [discount,setDiscount]=useState(defaults.discount??0);const [tax,setTax]=useState(defaults.tax??0);
  const totals=useMemo(()=>{const subtotal=items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.unitPrice||0),0);return{subtotal,total:Math.max(0,subtotal-Number(discount||0)+Number(tax||0))}},[items,discount,tax]);
  const update=(id:string,key:keyof Omit<Item,"id">,value:string|number)=>setItems((current)=>current.map((item)=>item.id===id?{...item,[key]:value}:item));
  const add=()=>{dirtyRef.current=true;setItems((current)=>[...current,{id:crypto.randomUUID(),title:"",description:"",quantity:1,unitPrice:0}])};
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirtyRef.current&&!pending){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[pending]);

  return <form action={action} className="space-y-6" onChange={()=>{dirtyRef.current=true}} onSubmit={()=>{dirtyRef.current=false}}><input type="hidden" name="quotationId" value={defaults.quotationId??""}/><input type="hidden" name="inquiryId" value={defaults.inquiryId??""}/><input type="hidden" name="clientId" value={defaults.clientId??""}/><input type="hidden" name="itemsJson" value={JSON.stringify(items.map((item)=>({ title:item.title, description:item.description, quantity:item.quantity, unitPrice:item.unitPrice })))}/>
    <Card><CardContent><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-secondary">Quotation</p><h2 className="mt-2 font-display text-xl font-extrabold">{defaults.quotationNumber ? `${defaults.quotationNumber} v${defaults.version}` : "Generated after save"}</h2></div><span className="text-sm font-semibold text-secondary">{defaults.quotationId?"DRAFT":"UNSAVED"}</span></div></CardContent></Card>
    <Card><CardContent><SectionTitle title="Client information"/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Client name" name="clientName" defaultValue={defaults.clientName}/><Field label="Company (optional)" name="companyName" required={false} defaultValue={defaults.companyName}/><Field label="Email" name="clientEmail" type="email" required={false} defaultValue={defaults.clientEmail}/><Field label="WhatsApp" name="clientPhone" required={false} defaultValue={defaults.clientPhone}/><Field label="Address (optional)" name="clientAddress" required={false} defaultValue={defaults.clientAddress} className="sm:col-span-2"/></div></CardContent></Card>
    <Card><CardContent><SectionTitle title="Project information"/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Project title" name="projectTitle" defaultValue={defaults.projectTitle} className="sm:col-span-2"/><Field label="Project type" name="projectType" required={false} defaultValue={defaults.projectType}/><Field label="Valid until" name="validUntil" type="date" defaultValue={defaults.validUntil}/><Field label="Estimated start" name="estimatedStartDate" type="date" required={false} defaultValue={defaults.estimatedStartDate}/><Field label="Estimated completion" name="estimatedCompletionAt" type="date" required={false} defaultValue={defaults.estimatedCompletionAt}/><Area label="Project summary" name="projectSummary" defaultValue={defaults.projectSummary} className="sm:col-span-2"/></div></CardContent></Card>
    <Card><CardContent><div className="flex items-center justify-between gap-4"><SectionTitle title="Quotation items"/><Button type="button" variant="outline" size="sm" onClick={add}><Plus className="size-4"/>Add item</Button></div><div className="mt-6 space-y-4">{items.map((item,index)=><div key={item.id} className="grid gap-3 rounded-[14px] border border-border p-4 md:grid-cols-[1fr_100px_180px_44px]"><div><Input aria-label={`Item ${index+1} title`} placeholder="Item title" value={item.title} onChange={(event)=>update(item.id,"title",event.target.value)}/><Textarea aria-label={`Item ${index+1} description`} placeholder="Description" className="mt-3 min-h-20" value={item.description} onChange={(event)=>update(item.id,"description",event.target.value)}/></div><label><span className="mb-2 block text-xs font-semibold text-secondary">Quantity</span><Input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(event)=>update(item.id,"quantity",Number(event.target.value))}/></label><label><span className="mb-2 block text-xs font-semibold text-secondary">Unit price</span><Input type="number" min="0" step="1" value={item.unitPrice} onChange={(event)=>update(item.id,"unitPrice",Number(event.target.value))}/><p className="mt-2 text-xs font-semibold text-primary">{formatIdr(item.quantity*item.unitPrice)}</p></label><Button type="button" variant="ghost" size="icon" aria-label="Remove item" disabled={items.length===1} onClick={()=>setItems((current)=>current.filter((entry)=>entry.id!==item.id))}><Trash2 className="size-4"/></Button></div>)}</div></CardContent></Card>
    <Card><CardContent><SectionTitle title="Price and payment terms"/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Discount" name="discount" type="number" min="0" value={discount} onChange={(e)=>setDiscount(Number(e.target.value))}/><Field label="Tax" name="tax" type="number" min="0" value={tax} onChange={(e)=>setTax(Number(e.target.value))}/><label><span className="mb-2 block text-sm font-semibold">Payment plan</span><select name="paymentPlanType" defaultValue={defaults.paymentPlanType??"DOWN_PAYMENT_AND_FINAL"} className={selectClass}><option value="FULL_PAYMENT">Full payment</option><option value="DOWN_PAYMENT_AND_FINAL">Down payment + final</option><option value="MILESTONE_BASED">Milestone based</option><option value="CUSTOM">Custom two-part</option></select></label><Field label="Custom first payment %" name="customFirstPayment" type="number" min="1" max="99" defaultValue={defaults.customFirstPayment??50}/></div><div className="mt-7 rounded-[14px] bg-accent-soft p-5"><div className="flex justify-between text-sm"><span>Subtotal</span><strong>{formatIdr(totals.subtotal)}</strong></div><div className="mt-2 flex justify-between text-sm"><span>Discount</span><strong>- {formatIdr(discount)}</strong></div><div className="mt-2 flex justify-between text-sm"><span>Tax</span><strong>{formatIdr(tax)}</strong></div><div className="mt-4 flex justify-between border-t border-primary/15 pt-4"><span className="font-semibold">Grand total</span><strong className="font-display text-2xl text-primary">{formatIdr(totals.total)}</strong></div><p className="mt-3 text-xs text-secondary">Preview only. The server recalculates every value before saving.</p></div></CardContent></Card>
    <Card><CardContent><SectionTitle title="Scope and terms"/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Area label="Scope included" name="scopeIncluded" defaultValue={defaults.scopeIncluded}/><Area label="Scope excluded (optional)" name="scopeExcluded" required={false} defaultValue={defaults.scopeExcluded}/><Field label="Revision limit" name="revisionLimit" type="number" min="0" required={false} defaultValue={defaults.revisionLimit}/><Field label="Maintenance days" name="maintenanceDays" type="number" min="0" required={false} defaultValue={defaults.maintenanceDays}/><Area label="Terms and conditions" name="terms" defaultValue={defaults.terms} className="sm:col-span-2"/><Area label="Additional notes (optional)" name="notes" required={false} defaultValue={defaults.notes} className="sm:col-span-2"/></div></CardContent></Card>
    {state.message&&<p role="alert" className="rounded-[10px] bg-[#fbe8e8] px-4 py-3 text-sm text-error">{state.message}</p>}<div className="sticky bottom-4 z-20 flex flex-col justify-end gap-3 rounded-[14px] border border-border bg-surface/95 p-4 shadow-xl backdrop-blur sm:flex-row"><Button type="submit" name="intent" value="DRAFT" variant="outline" disabled={pending}>{pending?"Saving…":"Save Draft"}</Button><Button type="submit" name="intent" value="SENT" disabled={pending}>{pending?"Saving…":"Save and Send"}</Button></div>
  </form>;
}
function SectionTitle({title}:{title:string}){return <h2 className="font-display text-xl font-extrabold">{title}</h2>}
function Field({label,name,type="text",required=true,className,...props}:{label:string;name:string;type?:string;required?:boolean;className?:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className={className}><span className="mb-2 block text-sm font-semibold">{label}</span><Input name={name} type={type} required={required} {...props}/></label>}
function Area({label,name,required=true,className,defaultValue}:{label:string;name:string;required?:boolean;className?:string;defaultValue?:string}){return <label className={className}><span className="mb-2 block text-sm font-semibold">{label}</span><Textarea name={name} required={required} defaultValue={defaultValue}/></label>}
