import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { rejectManualPaymentAction,verifyManualPaymentAction } from "@/features/payments/actions";
import { prisma } from "@/lib/db/prisma";
import { formatIdr } from "@/lib/utils";
export const dynamic="force-dynamic";
export default async function OwnerPaymentsPage(){const payments=await prisma.paymentAttempt.findMany({include:{client:true,invoice:true,project:true,files:true},orderBy:{createdAt:"desc"},take:100});return <><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Payments</p><h1 className="mt-3 font-display text-3xl font-extrabold">Provider attempts and manual verification.</h1><div className="mt-8 space-y-4">{payments.map((payment)=><Card key={payment.id} data-invoice={payment.invoice.invoiceNumber}><CardContent><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="font-display text-lg font-extrabold">{payment.invoice.invoiceNumber} · {payment.client.name}</p><p className="mt-1 text-xs text-secondary">{payment.provider} · {payment.project.title} · {payment.createdAt.toLocaleString("id-ID")}</p></div><div className="text-right"><p className="font-semibold text-primary">{formatIdr(payment.amount.toString())}</p><Badge className="mt-2">{payment.manualStatus??payment.status}</Badge></div></div>{payment.files.map((file)=><Link key={file.id} href={`/api/files/${file.id}/download`} className="mt-4 inline-block text-sm font-semibold text-primary hover:underline">View payment proof: {file.originalName}</Link>)}{payment.provider==="MANUAL"&&payment.manualStatus==="UNDER_VERIFICATION"&&<div className="mt-5 grid gap-3 border-t border-border pt-5 md:grid-cols-[auto_1fr_auto]"><form action={verifyManualPaymentAction}><input type="hidden" name="paymentId" value={payment.id}/><Button>Verify Payment</Button></form><form action={rejectManualPaymentAction} className="contents"><input type="hidden" name="paymentId" value={payment.id}/><Textarea name="reason" placeholder="Reason for rejection" required className="min-h-20"/><Button variant="danger">Reject Proof</Button></form></div>}</CardContent></Card>)}</div>{payments.length===0&&<p className="mt-8 rounded-[14px] border border-dashed border-border p-10 text-center text-sm text-secondary">No payment attempts yet.</p>}</>}
